/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "AggregatedPRSResourceSet-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_AggregatedPRSResourceSet_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AggregatedPRSResourceSet_Item, dl_PRS_ResourceSet_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_PRS_ResourceSet_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dl-PRS-ResourceSet-List"
		},
	{ ATF_POINTER, 1, offsetof(struct AggregatedPRSResourceSet_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_5638P6,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_AggregatedPRSResourceSet_Item_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_AggregatedPRSResourceSet_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AggregatedPRSResourceSet_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-PRS-ResourceSet-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_AggregatedPRSResourceSet_Item_specs_1 = {
	sizeof(struct AggregatedPRSResourceSet_Item),
	offsetof(struct AggregatedPRSResourceSet_Item, _asn_ctx),
	asn_MAP_AggregatedPRSResourceSet_Item_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_AggregatedPRSResourceSet_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AggregatedPRSResourceSet_Item = {
	"AggregatedPRSResourceSet-Item",
	"AggregatedPRSResourceSet-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_AggregatedPRSResourceSet_Item_tags_1,
	sizeof(asn_DEF_AggregatedPRSResourceSet_Item_tags_1)
		/sizeof(asn_DEF_AggregatedPRSResourceSet_Item_tags_1[0]), /* 1 */
	asn_DEF_AggregatedPRSResourceSet_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_AggregatedPRSResourceSet_Item_tags_1)
		/sizeof(asn_DEF_AggregatedPRSResourceSet_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AggregatedPRSResourceSet_Item_1,
	2,	/* Elements count */
	&asn_SPC_AggregatedPRSResourceSet_Item_specs_1	/* Additional specs */
};

