/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_AggregatedPosSRSResourceID_Item_H_
#define	_AggregatedPosSRSResourceID_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRSPosResourceID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* AggregatedPosSRSResourceID-Item */
typedef struct AggregatedPosSRSResourceID_Item {
	SRSPosResourceID_t	 sRSPosResource_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AggregatedPosSRSResourceID_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AggregatedPosSRSResourceID_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_AggregatedPosSRSResourceID_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_AggregatedPosSRSResourceID_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AggregatedPosSRSResourceID_Item_H_ */
#include <asn_internal.h>
