/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_Bandwidth_Aggregation_Request_Indication_H_
#define	_Bandwidth_Aggregation_Request_Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Bandwidth_Aggregation_Request_Indication {
	Bandwidth_Aggregation_Request_Indication_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Bandwidth_Aggregation_Request_Indication;

/* Bandwidth-Aggregation-Request-Indication */
typedef long	 Bandwidth_Aggregation_Request_Indication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Bandwidth_Aggregation_Request_Indication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Bandwidth_Aggregation_Request_Indication;
extern const asn_INTEGER_specifics_t asn_SPC_Bandwidth_Aggregation_Request_Indication_specs_1;
asn_struct_free_f Bandwidth_Aggregation_Request_Indication_free;
asn_struct_print_f Bandwidth_Aggregation_Request_Indication_print;
asn_constr_check_f Bandwidth_Aggregation_Request_Indication_constraint;
ber_type_decoder_f Bandwidth_Aggregation_Request_Indication_decode_ber;
der_type_encoder_f Bandwidth_Aggregation_Request_Indication_encode_der;
xer_type_decoder_f Bandwidth_Aggregation_Request_Indication_decode_xer;
xer_type_encoder_f Bandwidth_Aggregation_Request_Indication_encode_xer;
jer_type_encoder_f Bandwidth_Aggregation_Request_Indication_encode_jer;
per_type_decoder_f Bandwidth_Aggregation_Request_Indication_decode_uper;
per_type_encoder_f Bandwidth_Aggregation_Request_Indication_encode_uper;
per_type_decoder_f Bandwidth_Aggregation_Request_Indication_decode_aper;
per_type_encoder_f Bandwidth_Aggregation_Request_Indication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Bandwidth_Aggregation_Request_Indication_H_ */
#include <asn_internal.h>
