/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_Expected_UL_AoA_H_
#define	_Expected_UL_AoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Expected-Azimuth-AoA.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Expected_Zenith_AoA;
struct ProtocolExtensionContainer;

/* Expected-UL-AoA */
typedef struct Expected_UL_AoA {
	Expected_Azimuth_AoA_t	 expected_Azimuth_AoA;
	struct Expected_Zenith_AoA	*expected_Zenith_AoA;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Expected_UL_AoA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Expected_UL_AoA;
extern asn_SEQUENCE_specifics_t asn_SPC_Expected_UL_AoA_specs_1;
extern asn_TYPE_member_t asn_MBR_Expected_UL_AoA_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _Expected_UL_AoA_H_ */
#include <asn_internal.h>
