/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LoS_NLoSIndicatorSoft_H_
#define	_LoS_NLoSIndicatorSoft_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoS-NLoSIndicatorSoft */
typedef long	 LoS_NLoSIndicatorSoft_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LoS_NLoSIndicatorSoft_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LoS_NLoSIndicatorSoft;
asn_struct_free_f LoS_NLoSIndicatorSoft_free;
asn_struct_print_f LoS_NLoSIndicatorSoft_print;
asn_constr_check_f LoS_NLoSIndicatorSoft_constraint;
ber_type_decoder_f LoS_NLoSIndicatorSoft_decode_ber;
der_type_encoder_f LoS_NLoSIndicatorSoft_encode_der;
xer_type_decoder_f LoS_NLoSIndicatorSoft_decode_xer;
xer_type_encoder_f LoS_NLoSIndicatorSoft_encode_xer;
jer_type_encoder_f LoS_NLoSIndicatorSoft_encode_jer;
per_type_decoder_f LoS_NLoSIndicatorSoft_decode_uper;
per_type_encoder_f LoS_NLoSIndicatorSoft_encode_uper;
per_type_decoder_f LoS_NLoSIndicatorSoft_decode_aper;
per_type_encoder_f LoS_NLoSIndicatorSoft_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoS_NLoSIndicatorSoft_H_ */
#include <asn_internal.h>
