/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_MeasurementPeriodicityNR_AoA_H_
#define	_MeasurementPeriodicityNR_AoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementPeriodicityNR_AoA {
	MeasurementPeriodicityNR_AoA_ms160	= 0,
	MeasurementPeriodicityNR_AoA_ms320	= 1,
	MeasurementPeriodicityNR_AoA_ms640	= 2,
	MeasurementPeriodicityNR_AoA_ms1280	= 3,
	MeasurementPeriodicityNR_AoA_ms2560	= 4,
	MeasurementPeriodicityNR_AoA_ms5120	= 5,
	MeasurementPeriodicityNR_AoA_ms10240	= 6,
	MeasurementPeriodicityNR_AoA_ms20480	= 7,
	MeasurementPeriodicityNR_AoA_ms40960	= 8,
	MeasurementPeriodicityNR_AoA_ms61440	= 9,
	MeasurementPeriodicityNR_AoA_ms81920	= 10,
	MeasurementPeriodicityNR_AoA_ms368640	= 11,
	MeasurementPeriodicityNR_AoA_ms737280	= 12,
	MeasurementPeriodicityNR_AoA_ms1843200	= 13
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementPeriodicityNR_AoA;

/* MeasurementPeriodicityNR-AoA */
typedef long	 MeasurementPeriodicityNR_AoA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MeasurementPeriodicityNR_AoA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MeasurementPeriodicityNR_AoA;
extern const asn_INTEGER_specifics_t asn_SPC_MeasurementPeriodicityNR_AoA_specs_1;
asn_struct_free_f MeasurementPeriodicityNR_AoA_free;
asn_struct_print_f MeasurementPeriodicityNR_AoA_print;
asn_constr_check_f MeasurementPeriodicityNR_AoA_constraint;
ber_type_decoder_f MeasurementPeriodicityNR_AoA_decode_ber;
der_type_encoder_f MeasurementPeriodicityNR_AoA_encode_der;
xer_type_decoder_f MeasurementPeriodicityNR_AoA_decode_xer;
xer_type_encoder_f MeasurementPeriodicityNR_AoA_encode_xer;
jer_type_encoder_f MeasurementPeriodicityNR_AoA_encode_jer;
per_type_decoder_f MeasurementPeriodicityNR_AoA_decode_uper;
per_type_encoder_f MeasurementPeriodicityNR_AoA_encode_uper;
per_type_decoder_f MeasurementPeriodicityNR_AoA_decode_aper;
per_type_encoder_f MeasurementPeriodicityNR_AoA_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementPeriodicityNR_AoA_H_ */
#include <asn_internal.h>
