/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_Mobile_IAB_MT_UE_ID_H_
#define	_Mobile_IAB_MT_UE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Mobile-IAB-MT-UE-ID */
typedef OCTET_STRING_t	 Mobile_IAB_MT_UE_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Mobile_IAB_MT_UE_ID;
asn_struct_free_f Mobile_IAB_MT_UE_ID_free;
asn_struct_print_f Mobile_IAB_MT_UE_ID_print;
asn_constr_check_f Mobile_IAB_MT_UE_ID_constraint;
ber_type_decoder_f Mobile_IAB_MT_UE_ID_decode_ber;
der_type_encoder_f Mobile_IAB_MT_UE_ID_encode_der;
xer_type_decoder_f Mobile_IAB_MT_UE_ID_decode_xer;
xer_type_encoder_f Mobile_IAB_MT_UE_ID_encode_xer;
jer_type_encoder_f Mobile_IAB_MT_UE_ID_encode_jer;
per_type_decoder_f Mobile_IAB_MT_UE_ID_decode_uper;
per_type_encoder_f Mobile_IAB_MT_UE_ID_encode_uper;
per_type_decoder_f Mobile_IAB_MT_UE_ID_decode_aper;
per_type_encoder_f Mobile_IAB_MT_UE_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Mobile_IAB_MT_UE_ID_H_ */
#include <asn_internal.h>
