/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "Mobile-IAB-MT-UE-ID.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_Mobile_IAB_MT_UE_ID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Mobile_IAB_MT_UE_ID = {
	"Mobile-IAB-MT-UE-ID",
	"Mobile-IAB-MT-UE-ID",
	&asn_OP_OCTET_STRING,
	asn_DEF_Mobile_IAB_MT_UE_ID_tags_1,
	sizeof(asn_DEF_Mobile_IAB_MT_UE_ID_tags_1)
		/sizeof(asn_DEF_Mobile_IAB_MT_UE_ID_tags_1[0]), /* 1 */
	asn_DEF_Mobile_IAB_MT_UE_ID_tags_1,	/* Same as above */
	sizeof(asn_DEF_Mobile_IAB_MT_UE_ID_tags_1)
		/sizeof(asn_DEF_Mobile_IAB_MT_UE_ID_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		OCTET_STRING_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};

