/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-Containers"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_CIDMeasurementInitiationRequest_IEs;
struct E_CIDMeasurementInitiationResponse_IEs;
struct E_CIDMeasurementInitiationFailure_IEs;
struct E_CIDMeasurementFailureIndication_IEs;
struct E_CIDMeasurementReport_IEs;
struct E_CIDMeasurementTerminationCommand_IEs;
struct OTDOAInformationRequest_IEs;
struct OTDOAInformationResponse_IEs;
struct OTDOAInformationFailure_IEs;
struct AssistanceInformationControl_IEs;
struct AssistanceInformationFeedback_IEs;
struct ErrorIndication_IEs;
struct PositioningInformationRequest_IEs;
struct PositioningInformationResponse_IEs;
struct PositioningInformationFailure_IEs;
struct PositioningInformationUpdate_IEs;
struct MeasurementRequest_IEs;
struct MeasurementResponse_IEs;
struct MeasurementFailure_IEs;
struct MeasurementReport_IEs;
struct MeasurementUpdate_IEs;
struct MeasurementAbort_IEs;
struct MeasurementFailureIndication_IEs;
struct TRPInformationRequest_IEs;
struct TRPInformationResponse_IEs;
struct TRPInformationFailure_IEs;
struct PositioningActivationRequestIEs;
struct PositioningActivationResponseIEs;
struct PositioningActivationFailureIEs;
struct PositioningDeactivationIEs;
struct PRSConfigurationRequest_IEs;
struct PRSConfigurationResponse_IEs;
struct PRSConfigurationFailure_IEs;
struct MeasurementPreconfigurationRequired_IEs;
struct MeasurementPreconfigurationConfirm_IEs;
struct MeasurementPreconfigurationRefuse_IEs;
struct MeasurementActivation_IEs;
struct SRSInformationReservationNotification_IEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_5609P0 {
	A_SEQUENCE_OF(struct E_CIDMeasurementInitiationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P0_t;
typedef struct ProtocolIE_Container_5609P1 {
	A_SEQUENCE_OF(struct E_CIDMeasurementInitiationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P1_t;
typedef struct ProtocolIE_Container_5609P2 {
	A_SEQUENCE_OF(struct E_CIDMeasurementInitiationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P2_t;
typedef struct ProtocolIE_Container_5609P3 {
	A_SEQUENCE_OF(struct E_CIDMeasurementFailureIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P3_t;
typedef struct ProtocolIE_Container_5609P4 {
	A_SEQUENCE_OF(struct E_CIDMeasurementReport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P4_t;
typedef struct ProtocolIE_Container_5609P5 {
	A_SEQUENCE_OF(struct E_CIDMeasurementTerminationCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P5_t;
typedef struct ProtocolIE_Container_5609P6 {
	A_SEQUENCE_OF(struct OTDOAInformationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P6_t;
typedef struct ProtocolIE_Container_5609P7 {
	A_SEQUENCE_OF(struct OTDOAInformationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P7_t;
typedef struct ProtocolIE_Container_5609P8 {
	A_SEQUENCE_OF(struct OTDOAInformationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P8_t;
typedef struct ProtocolIE_Container_5609P9 {
	A_SEQUENCE_OF(struct AssistanceInformationControl_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P9_t;
typedef struct ProtocolIE_Container_5609P10 {
	A_SEQUENCE_OF(struct AssistanceInformationFeedback_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P10_t;
typedef struct ProtocolIE_Container_5609P11 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P11_t;
typedef struct ProtocolIE_Container_5609P12 {
	A_SEQUENCE_OF(struct PositioningInformationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P12_t;
typedef struct ProtocolIE_Container_5609P13 {
	A_SEQUENCE_OF(struct PositioningInformationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P13_t;
typedef struct ProtocolIE_Container_5609P14 {
	A_SEQUENCE_OF(struct PositioningInformationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P14_t;
typedef struct ProtocolIE_Container_5609P15 {
	A_SEQUENCE_OF(struct PositioningInformationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P15_t;
typedef struct ProtocolIE_Container_5609P16 {
	A_SEQUENCE_OF(struct MeasurementRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P16_t;
typedef struct ProtocolIE_Container_5609P17 {
	A_SEQUENCE_OF(struct MeasurementResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P17_t;
typedef struct ProtocolIE_Container_5609P18 {
	A_SEQUENCE_OF(struct MeasurementFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P18_t;
typedef struct ProtocolIE_Container_5609P19 {
	A_SEQUENCE_OF(struct MeasurementReport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P19_t;
typedef struct ProtocolIE_Container_5609P20 {
	A_SEQUENCE_OF(struct MeasurementUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P20_t;
typedef struct ProtocolIE_Container_5609P21 {
	A_SEQUENCE_OF(struct MeasurementAbort_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P21_t;
typedef struct ProtocolIE_Container_5609P22 {
	A_SEQUENCE_OF(struct MeasurementFailureIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P22_t;
typedef struct ProtocolIE_Container_5609P23 {
	A_SEQUENCE_OF(struct TRPInformationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P23_t;
typedef struct ProtocolIE_Container_5609P24 {
	A_SEQUENCE_OF(struct TRPInformationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P24_t;
typedef struct ProtocolIE_Container_5609P25 {
	A_SEQUENCE_OF(struct TRPInformationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P25_t;
typedef struct ProtocolIE_Container_5609P26 {
	A_SEQUENCE_OF(struct PositioningActivationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P26_t;
typedef struct ProtocolIE_Container_5609P27 {
	A_SEQUENCE_OF(struct PositioningActivationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P27_t;
typedef struct ProtocolIE_Container_5609P28 {
	A_SEQUENCE_OF(struct PositioningActivationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P28_t;
typedef struct ProtocolIE_Container_5609P29 {
	A_SEQUENCE_OF(struct PositioningDeactivationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P29_t;
typedef struct ProtocolIE_Container_5609P30 {
	A_SEQUENCE_OF(struct PRSConfigurationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P30_t;
typedef struct ProtocolIE_Container_5609P31 {
	A_SEQUENCE_OF(struct PRSConfigurationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P31_t;
typedef struct ProtocolIE_Container_5609P32 {
	A_SEQUENCE_OF(struct PRSConfigurationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P32_t;
typedef struct ProtocolIE_Container_5609P33 {
	A_SEQUENCE_OF(struct MeasurementPreconfigurationRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P33_t;
typedef struct ProtocolIE_Container_5609P34 {
	A_SEQUENCE_OF(struct MeasurementPreconfigurationConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P34_t;
typedef struct ProtocolIE_Container_5609P35 {
	A_SEQUENCE_OF(struct MeasurementPreconfigurationRefuse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P35_t;
typedef struct ProtocolIE_Container_5609P36 {
	A_SEQUENCE_OF(struct MeasurementActivation_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P36_t;
typedef struct ProtocolIE_Container_5609P37 {
	A_SEQUENCE_OF(struct SRSInformationReservationNotification_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5609P37_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5609P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5609P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5609P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5609P37_constr_75;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
