/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_PRSInformationPos_H_
#define	_PRSInformationPos_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PRS-ID.h"
#include "PRS-Resource-Set-ID.h"
#include "PRS-Resource-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PRSInformationPos */
typedef struct PRSInformationPos {
	PRS_ID_t	 pRS_IDPos;
	PRS_Resource_Set_ID_t	 pRS_Resource_Set_IDPos;
	PRS_Resource_ID_t	*pRS_Resource_IDPos;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PRSInformationPos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PRSInformationPos;
extern asn_SEQUENCE_specifics_t asn_SPC_PRSInformationPos_specs_1;
extern asn_TYPE_member_t asn_MBR_PRSInformationPos_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PRSInformationPos_H_ */
#include <asn_internal.h>
