/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "PRSResource-QCLSourcePRS.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_PRSResource_QCLSourcePRS_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PRSResource_QCLSourcePRS, qCLSourcePRSResourceSetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRS_Resource_Set_ID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qCLSourcePRSResourceSetID"
		},
	{ ATF_POINTER, 2, offsetof(struct PRSResource_QCLSourcePRS, qCLSourcePRSResourceID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PRS_Resource_ID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qCLSourcePRSResourceID"
		},
	{ ATF_POINTER, 1, offsetof(struct PRSResource_QCLSourcePRS, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_5638P70,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_PRSResource_QCLSourcePRS_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_PRSResource_QCLSourcePRS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PRSResource_QCLSourcePRS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* qCLSourcePRSResourceSetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* qCLSourcePRSResourceID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_PRSResource_QCLSourcePRS_specs_1 = {
	sizeof(struct PRSResource_QCLSourcePRS),
	offsetof(struct PRSResource_QCLSourcePRS, _asn_ctx),
	asn_MAP_PRSResource_QCLSourcePRS_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PRSResource_QCLSourcePRS_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PRSResource_QCLSourcePRS = {
	"PRSResource-QCLSourcePRS",
	"PRSResource-QCLSourcePRS",
	&asn_OP_SEQUENCE,
	asn_DEF_PRSResource_QCLSourcePRS_tags_1,
	sizeof(asn_DEF_PRSResource_QCLSourcePRS_tags_1)
		/sizeof(asn_DEF_PRSResource_QCLSourcePRS_tags_1[0]), /* 1 */
	asn_DEF_PRSResource_QCLSourcePRS_tags_1,	/* Same as above */
	sizeof(asn_DEF_PRSResource_QCLSourcePRS_tags_1)
		/sizeof(asn_DEF_PRSResource_QCLSourcePRS_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PRSResource_QCLSourcePRS_1,
	3,	/* Elements count */
	&asn_SPC_PRSResource_QCLSourcePRS_specs_1	/* Additional specs */
};

