/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_Remote_UE_Indication_Request_H_
#define	_Remote_UE_Indication_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Remote_UE_Indication_Request {
	Remote_UE_Indication_Request_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Remote_UE_Indication_Request;

/* Remote-UE-Indication-Request */
typedef long	 Remote_UE_Indication_Request_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Remote_UE_Indication_Request_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Remote_UE_Indication_Request;
extern const asn_INTEGER_specifics_t asn_SPC_Remote_UE_Indication_Request_specs_1;
asn_struct_free_f Remote_UE_Indication_Request_free;
asn_struct_print_f Remote_UE_Indication_Request_print;
asn_constr_check_f Remote_UE_Indication_Request_constraint;
ber_type_decoder_f Remote_UE_Indication_Request_decode_ber;
der_type_encoder_f Remote_UE_Indication_Request_encode_der;
xer_type_decoder_f Remote_UE_Indication_Request_decode_xer;
xer_type_encoder_f Remote_UE_Indication_Request_encode_xer;
jer_type_encoder_f Remote_UE_Indication_Request_encode_jer;
per_type_decoder_f Remote_UE_Indication_Request_decode_uper;
per_type_encoder_f Remote_UE_Indication_Request_encode_uper;
per_type_decoder_f Remote_UE_Indication_Request_decode_aper;
per_type_encoder_f Remote_UE_Indication_Request_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Remote_UE_Indication_Request_H_ */
#include <asn_internal.h>
