/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_RepetitionFactorExtended_H_
#define	_RepetitionFactorExtended_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RepetitionFactorExtended {
	RepetitionFactorExtended_n3	= 0,
	RepetitionFactorExtended_n5	= 1,
	RepetitionFactorExtended_n6	= 2,
	RepetitionFactorExtended_n7	= 3,
	RepetitionFactorExtended_n8	= 4,
	RepetitionFactorExtended_n10	= 5,
	RepetitionFactorExtended_n12	= 6,
	RepetitionFactorExtended_n14	= 7
	/*
	 * Enumeration is extensible
	 */
} e_RepetitionFactorExtended;

/* RepetitionFactorExtended */
typedef long	 RepetitionFactorExtended_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RepetitionFactorExtended_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RepetitionFactorExtended;
extern const asn_INTEGER_specifics_t asn_SPC_RepetitionFactorExtended_specs_1;
asn_struct_free_f RepetitionFactorExtended_free;
asn_struct_print_f RepetitionFactorExtended_print;
asn_constr_check_f RepetitionFactorExtended_constraint;
ber_type_decoder_f RepetitionFactorExtended_decode_ber;
der_type_encoder_f RepetitionFactorExtended_encode_der;
xer_type_decoder_f RepetitionFactorExtended_decode_xer;
xer_type_encoder_f RepetitionFactorExtended_encode_xer;
jer_type_encoder_f RepetitionFactorExtended_encode_jer;
per_type_decoder_f RepetitionFactorExtended_decode_uper;
per_type_encoder_f RepetitionFactorExtended_encode_uper;
per_type_decoder_f RepetitionFactorExtended_decode_aper;
per_type_encoder_f RepetitionFactorExtended_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RepetitionFactorExtended_H_ */
#include <asn_internal.h>
