/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_ResourceTypePeriodicPos_H_
#define	_ResourceTypePeriodicPos_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SRSPeriodicity.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ResourceTypePeriodicPos */
typedef struct ResourceTypePeriodicPos {
	SRSPeriodicity_t	 sRSPeriodicity;
	long	 offset;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceTypePeriodicPos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceTypePeriodicPos;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceTypePeriodicPos_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceTypePeriodicPos_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceTypePeriodicPos_H_ */
#include <asn_internal.h>
