/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_ResultSS_RSRP_Item_H_
#define	_ResultSS_RSRP_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR-PCI.h"
#include "NR-ARFCN.h"
#include "ValueRSRP-NR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CGI_NR;
struct ResultSS_RSRP_PerSSB;
struct ProtocolExtensionContainer;

/* ResultSS-RSRP-Item */
typedef struct ResultSS_RSRP_Item {
	NR_PCI_t	 nR_PCI;
	NR_ARFCN_t	 nR_ARFCN;
	struct CGI_NR	*cGI_NR;	/* OPTIONAL */
	ValueRSRP_NR_t	*valueSS_RSRP_Cell;	/* OPTIONAL */
	struct ResultSS_RSRP_PerSSB	*sS_RSRP_PerSSB;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResultSS_RSRP_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResultSS_RSRP_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_ResultSS_RSRP_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_ResultSS_RSRP_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ResultSS_RSRP_Item_H_ */
#include <asn_internal.h>
