/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_SlotOffsetRemainingHops_H_
#define	_SlotOffsetRemainingHops_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SlotOffsetRemainingHops_PR {
	SlotOffsetRemainingHops_PR_NOTHING,	/* No components present */
	SlotOffsetRemainingHops_PR_aperiodic,
	SlotOffsetRemainingHops_PR_semi_persistent,
	SlotOffsetRemainingHops_PR_periodic,
	SlotOffsetRemainingHops_PR_choice_extension
} SlotOffsetRemainingHops_PR;

/* Forward declarations */
struct SlotOffsetRemainingHopsAperiodic;
struct SlotOffsetRemainingHopsSemiPersistent;
struct SlotOffsetRemainingHopsPeriodic;
struct ProtocolIE_Single_Container;

/* SlotOffsetRemainingHops */
typedef struct SlotOffsetRemainingHops {
	SlotOffsetRemainingHops_PR present;
	union SlotOffsetRemainingHops_u {
		struct SlotOffsetRemainingHopsAperiodic	*aperiodic;
		struct SlotOffsetRemainingHopsSemiPersistent	*semi_persistent;
		struct SlotOffsetRemainingHopsPeriodic	*periodic;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SlotOffsetRemainingHops_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SlotOffsetRemainingHops;
extern asn_CHOICE_specifics_t asn_SPC_SlotOffsetRemainingHops_specs_1;
extern asn_TYPE_member_t asn_MBR_SlotOffsetRemainingHops_1[4];
extern asn_per_constraints_t asn_PER_type_SlotOffsetRemainingHops_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SlotOffsetRemainingHops_H_ */
#include <asn_internal.h>
