/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_SlotOffsetForRemainingHopsList_H_
#define	_SlotOffsetForRemainingHopsList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SlotOffsetForRemainingHopsItem;

/* SlotOffsetForRemainingHopsList */
typedef struct SlotOffsetForRemainingHopsList {
	A_SEQUENCE_OF(struct SlotOffsetForRemainingHopsItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SlotOffsetForRemainingHopsList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SlotOffsetForRemainingHopsList;
extern asn_SET_OF_specifics_t asn_SPC_SlotOffsetForRemainingHopsList_specs_1;
extern asn_TYPE_member_t asn_MBR_SlotOffsetForRemainingHopsList_1[1];
extern asn_per_constraints_t asn_PER_type_SlotOffsetForRemainingHopsList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SlotOffsetForRemainingHopsList_H_ */
#include <asn_internal.h>
