/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_SRSResourceTypeChoice_H_
#define	_SRSResourceTypeChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SRSResourceTypeChoice_PR {
	SRSResourceTypeChoice_PR_NOTHING,	/* No components present */
	SRSResourceTypeChoice_PR_sRSResourceInfo,
	SRSResourceTypeChoice_PR_posSRSResourceInfo
	/* Extensions may appear below */
	
} SRSResourceTypeChoice_PR;

/* Forward declarations */
struct SRSInfo;
struct PosSRSInfo;

/* SRSResourceTypeChoice */
typedef struct SRSResourceTypeChoice {
	SRSResourceTypeChoice_PR present;
	union SRSResourceTypeChoice_u {
		struct SRSInfo	*sRSResourceInfo;
		struct PosSRSInfo	*posSRSResourceInfo;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRSResourceTypeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRSResourceTypeChoice;
extern asn_CHOICE_specifics_t asn_SPC_SRSResourceTypeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_SRSResourceTypeChoice_1[2];
extern asn_per_constraints_t asn_PER_type_SRSResourceTypeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SRSResourceTypeChoice_H_ */
#include <asn_internal.h>
