/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_StartRBHopping_H_
#define	_StartRBHopping_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StartRBHopping {
	StartRBHopping_enable	= 0
} e_StartRBHopping;

/* StartRBHopping */
typedef long	 StartRBHopping_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_StartRBHopping_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_StartRBHopping;
extern const asn_INTEGER_specifics_t asn_SPC_StartRBHopping_specs_1;
asn_struct_free_f StartRBHopping_free;
asn_struct_print_f StartRBHopping_print;
asn_constr_check_f StartRBHopping_constraint;
ber_type_decoder_f StartRBHopping_decode_ber;
der_type_encoder_f StartRBHopping_encode_der;
xer_type_decoder_f StartRBHopping_decode_xer;
xer_type_encoder_f StartRBHopping_encode_xer;
jer_type_encoder_f StartRBHopping_encode_jer;
per_type_decoder_f StartRBHopping_decode_uper;
per_type_encoder_f StartRBHopping_encode_uper;
per_type_decoder_f StartRBHopping_decode_aper;
per_type_encoder_f StartRBHopping_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _StartRBHopping_H_ */
#include <asn_internal.h>
