/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_TimeWindowPeriodicitySRS_H_
#define	_TimeWindowPeriodicitySRS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeWindowPeriodicitySRS {
	TimeWindowPeriodicitySRS_ms0dot125	= 0,
	TimeWindowPeriodicitySRS_ms0dot25	= 1,
	TimeWindowPeriodicitySRS_ms0dot5	= 2,
	TimeWindowPeriodicitySRS_ms0dot625	= 3,
	TimeWindowPeriodicitySRS_ms1	= 4,
	TimeWindowPeriodicitySRS_ms1dot25	= 5,
	TimeWindowPeriodicitySRS_ms2	= 6,
	TimeWindowPeriodicitySRS_ms2dot5	= 7,
	TimeWindowPeriodicitySRS_ms4	= 8,
	TimeWindowPeriodicitySRS_ms5	= 9,
	TimeWindowPeriodicitySRS_ms8	= 10,
	TimeWindowPeriodicitySRS_ms10	= 11,
	TimeWindowPeriodicitySRS_ms16	= 12,
	TimeWindowPeriodicitySRS_ms20	= 13,
	TimeWindowPeriodicitySRS_ms32	= 14,
	TimeWindowPeriodicitySRS_ms40	= 15,
	TimeWindowPeriodicitySRS_ms64	= 16,
	TimeWindowPeriodicitySRS_ms80	= 17,
	TimeWindowPeriodicitySRS_ms160	= 18,
	TimeWindowPeriodicitySRS_ms320	= 19,
	TimeWindowPeriodicitySRS_ms640	= 20,
	TimeWindowPeriodicitySRS_ms1280	= 21,
	TimeWindowPeriodicitySRS_ms2560	= 22,
	TimeWindowPeriodicitySRS_ms5120	= 23,
	TimeWindowPeriodicitySRS_ms10240	= 24
	/*
	 * Enumeration is extensible
	 */
} e_TimeWindowPeriodicitySRS;

/* TimeWindowPeriodicitySRS */
typedef long	 TimeWindowPeriodicitySRS_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeWindowPeriodicitySRS_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeWindowPeriodicitySRS;
extern const asn_INTEGER_specifics_t asn_SPC_TimeWindowPeriodicitySRS_specs_1;
asn_struct_free_f TimeWindowPeriodicitySRS_free;
asn_struct_print_f TimeWindowPeriodicitySRS_print;
asn_constr_check_f TimeWindowPeriodicitySRS_constraint;
ber_type_decoder_f TimeWindowPeriodicitySRS_decode_ber;
der_type_encoder_f TimeWindowPeriodicitySRS_encode_der;
xer_type_decoder_f TimeWindowPeriodicitySRS_decode_xer;
xer_type_encoder_f TimeWindowPeriodicitySRS_encode_xer;
jer_type_encoder_f TimeWindowPeriodicitySRS_encode_jer;
per_type_decoder_f TimeWindowPeriodicitySRS_decode_uper;
per_type_encoder_f TimeWindowPeriodicitySRS_encode_uper;
per_type_decoder_f TimeWindowPeriodicitySRS_decode_aper;
per_type_encoder_f TimeWindowPeriodicitySRS_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeWindowPeriodicitySRS_H_ */
#include <asn_internal.h>
