/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_TimeWindowInformation_SRS_Item_H_
#define	_TimeWindowInformation_SRS_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeWindowStartSRS.h"
#include "TimeWindowDurationSRS.h"
#include <NativeEnumerated.h>
#include "TimeWindowPeriodicitySRS.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimeWindowInformation_SRS_Item__timeWindowType {
	TimeWindowInformation_SRS_Item__timeWindowType_single	= 0,
	TimeWindowInformation_SRS_Item__timeWindowType_periodic	= 1
	/*
	 * Enumeration is extensible
	 */
} e_TimeWindowInformation_SRS_Item__timeWindowType;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* TimeWindowInformation-SRS-Item */
typedef struct TimeWindowInformation_SRS_Item {
	TimeWindowStartSRS_t	 timeWindowStartSRS;
	TimeWindowDurationSRS_t	 timeWindowDurationSRS;
	long	 timeWindowType;
	TimeWindowPeriodicitySRS_t	*timeWindowPeriodicitySRS;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimeWindowInformation_SRS_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_timeWindowType_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_TimeWindowInformation_SRS_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_TimeWindowInformation_SRS_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_TimeWindowInformation_SRS_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TimeWindowInformation_SRS_Item_H_ */
#include <asn_internal.h>
