/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_TimingErrorMargin_H_
#define	_TimingErrorMargin_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TimingErrorMargin {
	TimingErrorMargin_tc0	= 0,
	TimingErrorMargin_tc2	= 1,
	TimingErrorMargin_tc4	= 2,
	TimingErrorMargin_tc6	= 3,
	TimingErrorMargin_tc8	= 4,
	TimingErrorMargin_tc12	= 5,
	TimingErrorMargin_tc16	= 6,
	TimingErrorMargin_tc20	= 7,
	TimingErrorMargin_tc24	= 8,
	TimingErrorMargin_tc32	= 9,
	TimingErrorMargin_tc40	= 10,
	TimingErrorMargin_tc48	= 11,
	TimingErrorMargin_tc56	= 12,
	TimingErrorMargin_tc64	= 13,
	TimingErrorMargin_tc72	= 14,
	TimingErrorMargin_tc80	= 15
	/*
	 * Enumeration is extensible
	 */
} e_TimingErrorMargin;

/* TimingErrorMargin */
typedef long	 TimingErrorMargin_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimingErrorMargin_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimingErrorMargin;
extern const asn_INTEGER_specifics_t asn_SPC_TimingErrorMargin_specs_1;
asn_struct_free_f TimingErrorMargin_free;
asn_struct_print_f TimingErrorMargin_print;
asn_constr_check_f TimingErrorMargin_constraint;
ber_type_decoder_f TimingErrorMargin_decode_ber;
der_type_encoder_f TimingErrorMargin_encode_der;
xer_type_decoder_f TimingErrorMargin_decode_xer;
xer_type_encoder_f TimingErrorMargin_encode_xer;
jer_type_encoder_f TimingErrorMargin_encode_jer;
per_type_decoder_f TimingErrorMargin_decode_uper;
per_type_encoder_f TimingErrorMargin_encode_uper;
per_type_decoder_f TimingErrorMargin_decode_aper;
per_type_encoder_f TimingErrorMargin_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimingErrorMargin_H_ */
#include <asn_internal.h>
