/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_TRPType_H_
#define	_TRPType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TRPType {
	TRPType_prsOnlyTP	= 0,
	TRPType_srsOnlyRP	= 1,
	TRPType_tp	= 2,
	TRPType_rp	= 3,
	TRPType_trp	= 4,
	/*
	 * Enumeration is extensible
	 */
	TRPType_mobile_trp	= 5
} e_TRPType;

/* TRPType */
typedef long	 TRPType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TRPType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TRPType;
extern const asn_INTEGER_specifics_t asn_SPC_TRPType_specs_1;
asn_struct_free_f TRPType_free;
asn_struct_print_f TRPType_print;
asn_constr_check_f TRPType_constraint;
ber_type_decoder_f TRPType_decode_ber;
der_type_encoder_f TRPType_encode_der;
xer_type_decoder_f TRPType_decode_xer;
xer_type_encoder_f TRPType_encode_xer;
jer_type_encoder_f TRPType_encode_jer;
per_type_decoder_f TRPType_decode_uper;
per_type_encoder_f TRPType_encode_uper;
per_type_decoder_f TRPType_decode_aper;
per_type_encoder_f TRPType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TRPType_H_ */
#include <asn_internal.h>
