/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_UE_TEG_ReportingPeriodicity_H_
#define	_UE_TEG_ReportingPeriodicity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_TEG_ReportingPeriodicity {
	UE_TEG_ReportingPeriodicity_ms160	= 0,
	UE_TEG_ReportingPeriodicity_ms320	= 1,
	UE_TEG_ReportingPeriodicity_ms1280	= 2,
	UE_TEG_ReportingPeriodicity_ms2560	= 3,
	UE_TEG_ReportingPeriodicity_ms61440	= 4,
	UE_TEG_ReportingPeriodicity_ms81920	= 5,
	UE_TEG_ReportingPeriodicity_ms368640	= 6,
	UE_TEG_ReportingPeriodicity_ms737280	= 7
	/*
	 * Enumeration is extensible
	 */
} e_UE_TEG_ReportingPeriodicity;

/* UE-TEG-ReportingPeriodicity */
typedef long	 UE_TEG_ReportingPeriodicity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UE_TEG_ReportingPeriodicity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UE_TEG_ReportingPeriodicity;
extern const asn_INTEGER_specifics_t asn_SPC_UE_TEG_ReportingPeriodicity_specs_1;
asn_struct_free_f UE_TEG_ReportingPeriodicity_free;
asn_struct_print_f UE_TEG_ReportingPeriodicity_print;
asn_constr_check_f UE_TEG_ReportingPeriodicity_constraint;
ber_type_decoder_f UE_TEG_ReportingPeriodicity_decode_ber;
der_type_encoder_f UE_TEG_ReportingPeriodicity_encode_der;
xer_type_decoder_f UE_TEG_ReportingPeriodicity_decode_xer;
xer_type_encoder_f UE_TEG_ReportingPeriodicity_encode_xer;
jer_type_encoder_f UE_TEG_ReportingPeriodicity_encode_jer;
per_type_decoder_f UE_TEG_ReportingPeriodicity_decode_uper;
per_type_encoder_f UE_TEG_ReportingPeriodicity_encode_uper;
per_type_decoder_f UE_TEG_ReportingPeriodicity_decode_aper;
per_type_encoder_f UE_TEG_ReportingPeriodicity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_TEG_ReportingPeriodicity_H_ */
#include <asn_internal.h>
