/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_Uncertainty_range_ZoA_H_
#define	_Uncertainty_range_ZoA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Uncertainty-range-ZoA */
typedef long	 Uncertainty_range_ZoA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Uncertainty_range_ZoA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Uncertainty_range_ZoA;
asn_struct_free_f Uncertainty_range_ZoA_free;
asn_struct_print_f Uncertainty_range_ZoA_print;
asn_constr_check_f Uncertainty_range_ZoA_constraint;
ber_type_decoder_f Uncertainty_range_ZoA_decode_ber;
der_type_encoder_f Uncertainty_range_ZoA_encode_der;
xer_type_decoder_f Uncertainty_range_ZoA_decode_xer;
xer_type_encoder_f Uncertainty_range_ZoA_encode_xer;
jer_type_encoder_f Uncertainty_range_ZoA_encode_jer;
per_type_decoder_f Uncertainty_range_ZoA_decode_uper;
per_type_encoder_f Uncertainty_range_ZoA_encode_uper;
per_type_decoder_f Uncertainty_range_ZoA_decode_aper;
per_type_encoder_f Uncertainty_range_ZoA_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Uncertainty_range_ZoA_H_ */
#include <asn_internal.h>
