/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NRPPA-IEs"
 * 	found in "/tmp/claude-1000/-home-seven-kriish-ntn-upstream-OCUDU-RAN/a73dcc0d-9300-4dd6-8edd-269c760cd4a8/scratchpad/spec/38455-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_ValidityAreaSpecificSRSInformationExtended_H_
#define	_ValidityAreaSpecificSRSInformationExtended_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PosSRSResource_List;
struct PosSRSResourceSet_List;
struct ProtocolExtensionContainer;

/* ValidityAreaSpecificSRSInformationExtended */
typedef struct ValidityAreaSpecificSRSInformationExtended {
	struct PosSRSResource_List	*posSRSResource_List;	/* OPTIONAL */
	struct PosSRSResourceSet_List	*posSRSResourceSet_List;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ValidityAreaSpecificSRSInformationExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ValidityAreaSpecificSRSInformationExtended;
extern asn_SEQUENCE_specifics_t asn_SPC_ValidityAreaSpecificSRSInformationExtended_specs_1;
extern asn_TYPE_member_t asn_MBR_ValidityAreaSpecificSRSInformationExtended_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ValidityAreaSpecificSRSInformationExtended_H_ */
#include <asn_internal.h>
