/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "LPP_DL-PRS-Resource-ARP-Element-r16.h"

#include "LPP_RelativeLocation-r16.h"
#include "LPP_RelativeCartesianLocation-r18.h"
#include "LPP_NR-IntegrityLocationBounds-r18.h"
static asn_TYPE_member_t asn_MBR_LPP_ext1_4[] = {
	{ ATF_POINTER, 2, offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16__ext1, dl_PRS_Resource_ARP_locationCartesian_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_RelativeCartesianLocation_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dl-PRS-Resource-ARP-locationCartesian-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16__ext1, nr_IntegrityDL_PRS_ResourceARP_LocationBounds_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NR_IntegrityLocationBounds_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-IntegrityDL-PRS-ResourceARP-LocationBounds-r18"
		},
};
static const int asn_MAP_LPP_ext1_oms_4[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_LPP_ext1_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_ext1_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-PRS-Resource-ARP-locationCartesian-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nr-IntegrityDL-PRS-ResourceARP-LocationBounds-r18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LPP_ext1_specs_4 = {
	sizeof(struct LPP_DL_PRS_Resource_ARP_Element_r16__ext1),
	offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16__ext1, _asn_ctx),
	asn_MAP_LPP_ext1_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_LPP_ext1_oms_4,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_LPP_ext1_4 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_ext1_tags_4,
	sizeof(asn_DEF_LPP_ext1_tags_4)
		/sizeof(asn_DEF_LPP_ext1_tags_4[0]) - 1, /* 1 */
	asn_DEF_LPP_ext1_tags_4,	/* Same as above */
	sizeof(asn_DEF_LPP_ext1_tags_4)
		/sizeof(asn_DEF_LPP_ext1_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_ext1_4,
	2,	/* Elements count */
	&asn_SPC_LPP_ext1_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LPP_DL_PRS_Resource_ARP_Element_r16_1[] = {
	{ ATF_POINTER, 2, offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16, dl_PRS_Resource_ARP_location_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_RelativeLocation_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dl-PRS-Resource-ARP-location-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16, ext1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_LPP_ext1_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext1"
		},
};
static const int asn_MAP_LPP_DL_PRS_Resource_ARP_Element_r16_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_DL_PRS_Resource_ARP_Element_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-PRS-Resource-ARP-location-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ext1 */
};
asn_SEQUENCE_specifics_t asn_SPC_LPP_DL_PRS_Resource_ARP_Element_r16_specs_1 = {
	sizeof(struct LPP_DL_PRS_Resource_ARP_Element_r16),
	offsetof(struct LPP_DL_PRS_Resource_ARP_Element_r16, _asn_ctx),
	asn_MAP_LPP_DL_PRS_Resource_ARP_Element_r16_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_LPP_DL_PRS_Resource_ARP_Element_r16_oms_1,	/* Optional members */
	1, 1,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16 = {
	"DL-PRS-Resource-ARP-Element-r16",
	"DL-PRS-Resource-ARP-Element-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1,
	sizeof(asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1)
		/sizeof(asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1[0]), /* 1 */
	asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1)
		/sizeof(asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_DL_PRS_Resource_ARP_Element_r16_1,
	2,	/* Elements count */
	&asn_SPC_LPP_DL_PRS_Resource_ARP_Element_r16_specs_1	/* Additional specs */
};

