/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_Multi_RTT_MeasCapabilityPerBand_r17_H_
#define	_LPP_Multi_RTT_MeasCapabilityPerBand_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_FreqBandIndicatorNR-r16.h"
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__supportOfDL_PRS_FirstPathRSRP_r17 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__supportOfDL_PRS_FirstPathRSRP_r17_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__supportOfDL_PRS_FirstPathRSRP_r17;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__dl_PRS_MeasRRC_Inactive_r17 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__dl_PRS_MeasRRC_Inactive_r17_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__dl_PRS_MeasRRC_Inactive_r17;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Connected_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Connected_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Connected_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Inactive_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Inactive_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfDL_PRS_BWA_RRC_Inactive_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_NTN_MeasAndReport_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_NTN_MeasAndReport_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_NTN_MeasAndReport_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Connected_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Connected_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Connected_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Inactive_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Inactive_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__nr_DL_PRS_RSCP_RRC_Inactive_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__assocSingleRx_Tx_WithUpToNsampleRSCP_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__assocSingleRx_Tx_WithUpToNsampleRSCP_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__assocSingleRx_Tx_WithUpToNsampleRSCP_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfSymbolTimeStampForRSCP_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfSymbolTimeStampForRSCP_r18_supported	= 0
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfSymbolTimeStampForRSCP_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus1	= 0,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus2	= 1,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus3	= 2,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus4	= 3,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus5	= 4,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18_minus6	= 5
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfFinerTimingReportGranularityForPRS_Meas_r18;
typedef enum LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18 {
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18_rx_tx	= 0,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18_rsrp	= 1,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18_rsrpp	= 2,
	LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18_rscp	= 3
} e_LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1__supportOfMeasurementsInTimeWindow_r18;

/* LPP_Multi-RTT-MeasCapabilityPerBand-r17 */
typedef struct LPP_Multi_RTT_MeasCapabilityPerBand_r17 {
	LPP_FreqBandIndicatorNR_r16_t	 freqBandIndicatorNR_r17;
	long	*supportOfDL_PRS_FirstPathRSRP_r17;	/* OPTIONAL */
	long	*dl_PRS_MeasRRC_Inactive_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_Multi_RTT_MeasCapabilityPerBand_r17__ext1 {
		long	*supportOfDL_PRS_BWA_RRC_Connected_r18;	/* OPTIONAL */
		long	*supportOfDL_PRS_BWA_RRC_Inactive_r18;	/* OPTIONAL */
		long	*nr_NTN_MeasAndReport_r18;	/* OPTIONAL */
		long	*nr_DL_PRS_RSCP_RRC_Connected_r18;	/* OPTIONAL */
		long	*nr_DL_PRS_RSCP_RRC_Inactive_r18;	/* OPTIONAL */
		long	*assocSingleRx_Tx_WithUpToNsampleRSCP_r18;	/* OPTIONAL */
		long	*supportOfSymbolTimeStampForRSCP_r18;	/* OPTIONAL */
		long	*supportOfFinerTimingReportGranularityForPRS_Meas_r18;	/* OPTIONAL */
		BIT_STRING_t	*supportOfMeasurementsInTimeWindow_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_Multi_RTT_MeasCapabilityPerBand_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfDL_PRS_FirstPathRSRP_r17_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_PRS_MeasRRC_Inactive_r17_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfDL_PRS_BWA_RRC_Connected_r18_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfDL_PRS_BWA_RRC_Inactive_r18_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_NTN_MeasAndReport_r18_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_DL_PRS_RSCP_RRC_Connected_r18_15;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_DL_PRS_RSCP_RRC_Inactive_r18_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_assocSingleRx_Tx_WithUpToNsampleRSCP_r18_19;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfSymbolTimeStampForRSCP_r18_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfFinerTimingReportGranularityForPRS_Meas_r18_23;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_Multi_RTT_MeasCapabilityPerBand_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_Multi_RTT_MeasCapabilityPerBand_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_Multi_RTT_MeasCapabilityPerBand_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_Multi_RTT_MeasCapabilityPerBand_r17_H_ */
#include <asn_internal.h>
