/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_CommonAssistData_H_
#define	_LPP_GNSS_CommonAssistData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_GNSS_ReferenceTime;
struct LPP_GNSS_ReferenceLocation;
struct LPP_GNSS_IonosphericModel;
struct LPP_GNSS_EarthOrientationParameters;
struct LPP_GNSS_RTK_ReferenceStationInfo_r15;
struct LPP_GNSS_RTK_CommonObservationInfo_r15;
struct LPP_GNSS_RTK_AuxiliaryStationData_r15;
struct LPP_GNSS_SSR_CorrectionPoints_r16;
struct LPP_GNSS_Integrity_ServiceParameters_r17;
struct LPP_GNSS_Integrity_ServiceAlert_r17;
struct LPP_GNSS_LOS_NLOS_GridPoints_r18;
struct LPP_GNSS_SSR_IOD_Update_r18;

/* LPP_GNSS-CommonAssistData */
typedef struct LPP_GNSS_CommonAssistData {
	struct LPP_GNSS_ReferenceTime	*gnss_ReferenceTime;	/* OPTIONAL */
	struct LPP_GNSS_ReferenceLocation	*gnss_ReferenceLocation;	/* OPTIONAL */
	struct LPP_GNSS_IonosphericModel	*gnss_IonosphericModel;	/* OPTIONAL */
	struct LPP_GNSS_EarthOrientationParameters	*gnss_EarthOrientationParameters;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_GNSS_CommonAssistData__ext1 {
		struct LPP_GNSS_RTK_ReferenceStationInfo_r15	*gnss_RTK_ReferenceStationInfo_r15;	/* OPTIONAL */
		struct LPP_GNSS_RTK_CommonObservationInfo_r15	*gnss_RTK_CommonObservationInfo_r15;	/* OPTIONAL */
		struct LPP_GNSS_RTK_AuxiliaryStationData_r15	*gnss_RTK_AuxiliaryStationData_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_GNSS_CommonAssistData__ext2 {
		struct LPP_GNSS_SSR_CorrectionPoints_r16	*gnss_SSR_CorrectionPoints_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_GNSS_CommonAssistData__ext3 {
		struct LPP_GNSS_Integrity_ServiceParameters_r17	*gnss_Integrity_ServiceParameters_r17;	/* OPTIONAL */
		struct LPP_GNSS_Integrity_ServiceAlert_r17	*gnss_Integrity_ServiceAlert_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	struct LPP_GNSS_CommonAssistData__ext4 {
		struct LPP_GNSS_LOS_NLOS_GridPoints_r18	*gnss_los_nlos_GridPoints_r18;	/* OPTIONAL */
		struct LPP_GNSS_SSR_IOD_Update_r18	*gnss_SSR_IOD_Update_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_CommonAssistData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_CommonAssistData;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_CommonAssistData_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_CommonAssistData_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_CommonAssistData_H_ */
#include <asn_internal.h>
