/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_DL_PRS_Resource_ARP_Element_r16_H_
#define	_LPP_DL_PRS_Resource_ARP_Element_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_RelativeLocation_r16;
struct LPP_RelativeCartesianLocation_r18;
struct LPP_NR_IntegrityLocationBounds_r18;

/* LPP_DL-PRS-Resource-ARP-Element-r16 */
typedef struct LPP_DL_PRS_Resource_ARP_Element_r16 {
	struct LPP_RelativeLocation_r16	*dl_PRS_Resource_ARP_location_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_DL_PRS_Resource_ARP_Element_r16__ext1 {
		struct LPP_RelativeCartesianLocation_r18	*dl_PRS_Resource_ARP_locationCartesian_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityLocationBounds_r18	*nr_IntegrityDL_PRS_ResourceARP_LocationBounds_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_DL_PRS_Resource_ARP_Element_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_DL_PRS_Resource_ARP_Element_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_DL_PRS_Resource_ARP_Element_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_DL_PRS_Resource_ARP_Element_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_DL_PRS_Resource_ARP_Element_r16_H_ */
#include <asn_internal.h>
