/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-Broadcast-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_IntegrityParameters_r18_H_
#define	_LPP_NR_IntegrityParameters_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_NR_IntegrityParametersTRP_LocationInfo_r18;
struct LPP_NR_IntegrityParametersDL_PRS_BeamInfo_r18;
struct LPP_NR_IntegrityParametersRTD_Info_r18;
struct LPP_NR_IntegrityParametersTRP_BeamAntennaInfo_r18;

/* LPP_NR-IntegrityParameters-r18 */
typedef struct LPP_NR_IntegrityParameters_r18 {
	struct LPP_NR_IntegrityParametersTRP_LocationInfo_r18	*nr_IntegrityParametersTRP_LocationInfo_r18;	/* OPTIONAL */
	struct LPP_NR_IntegrityParametersDL_PRS_BeamInfo_r18	*nr_IntegrityParametersDL_PRS_BeamInfo_r18;	/* OPTIONAL */
	struct LPP_NR_IntegrityParametersRTD_Info_r18	*nr_IntegrityParametersRTD_Info_r18;	/* OPTIONAL */
	struct LPP_NR_IntegrityParametersTRP_BeamAntennaInfo_r18	*nr_IntegrityParametersTRP_BeamAntennaInfo_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_IntegrityParameters_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_IntegrityParameters_r18;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_IntegrityParameters_r18_H_ */
#include <asn_internal.h>
