/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_PRU_DL_Info_r18_H_
#define	_LPP_NR_PRU_DL_Info_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_LocationCoordinates;
struct LPP_NR_DL_TDOA_SignalMeasurementInformation_r16;
struct LPP_NR_DL_AoD_SignalMeasurementInformation_r16;
struct LPP_NR_PRU_RSCP_MeasurementInformation_r18;

/* LPP_NR-PRU-DL-Info-r18 */
typedef struct LPP_NR_PRU_DL_Info_r18 {
	struct LPP_LocationCoordinates	*nr_PRU_LocationInfo_r18;	/* OPTIONAL */
	struct LPP_NR_DL_TDOA_SignalMeasurementInformation_r16	*nr_PRU_DL_TDOA_MeasInfo_r18;	/* OPTIONAL */
	struct LPP_NR_DL_AoD_SignalMeasurementInformation_r16	*nr_PRU_DL_AoD_MeasInfo_r18;	/* OPTIONAL */
	struct LPP_NR_PRU_RSCP_MeasurementInformation_r18	*nr_PRU_RSCP_MeasInfo_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_PRU_DL_Info_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_PRU_DL_Info_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_PRU_DL_Info_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_PRU_DL_Info_r18_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_PRU_DL_Info_r18_H_ */
#include <asn_internal.h>
