/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_ScheduledLocationTimeSupport_r17_H_
#define	_LPP_ScheduledLocationTimeSupport_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_ScheduledLocationTimeSupport_r17__utcTime_r17 {
	LPP_ScheduledLocationTimeSupport_r17__utcTime_r17_supported	= 0
} e_LPP_ScheduledLocationTimeSupport_r17__utcTime_r17;
typedef enum LPP_ScheduledLocationTimeSupport_r17__e_utraTime_r17 {
	LPP_ScheduledLocationTimeSupport_r17__e_utraTime_r17_supported	= 0
} e_LPP_ScheduledLocationTimeSupport_r17__e_utraTime_r17;
typedef enum LPP_ScheduledLocationTimeSupport_r17__nrTime_r17 {
	LPP_ScheduledLocationTimeSupport_r17__nrTime_r17_supported	= 0
} e_LPP_ScheduledLocationTimeSupport_r17__nrTime_r17;
typedef enum LPP_ScheduledLocationTimeSupport_r17__relativeTime_r17 {
	LPP_ScheduledLocationTimeSupport_r17__relativeTime_r17_supported	= 0
} e_LPP_ScheduledLocationTimeSupport_r17__relativeTime_r17;

/* Forward declarations */
struct LPP_GNSS_ID_Bitmap;

/* LPP_ScheduledLocationTimeSupport-r17 */
typedef struct LPP_ScheduledLocationTimeSupport_r17 {
	long	*utcTime_r17;	/* OPTIONAL */
	struct LPP_GNSS_ID_Bitmap	*gnssTime_r17;	/* OPTIONAL */
	long	*e_utraTime_r17;	/* OPTIONAL */
	long	*nrTime_r17;	/* OPTIONAL */
	long	*relativeTime_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_ScheduledLocationTimeSupport_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_utcTime_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_e_utraTime_r17_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nrTime_r17_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_relativeTime_r17_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_ScheduledLocationTimeSupport_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_ScheduledLocationTimeSupport_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_ScheduledLocationTimeSupport_r17_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ScheduledLocationTimeSupport_r17_H_ */
#include <asn_internal.h>
