/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_RelativeCartesianLocation_r18_H_
#define	_LPP_RelativeCartesianLocation_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "LPP_X-Value-r18.h"
#include "LPP_Y-Value-r18.h"
#include "LPP_Z-Value-r18.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18 {
	LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18_mm	= 0,
	LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18_cm	= 1,
	LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18_dm	= 2,
	LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18_m	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LPP_RelativeCartesianLocation_r18__cartesianCoordinatesUnits_r18;

/* Forward declarations */
struct LPP_LocationUncertainty_r16;

/* LPP_RelativeCartesianLocation-r18 */
typedef struct LPP_RelativeCartesianLocation_r18 {
	long	 cartesianCoordinatesUnits_r18;
	LPP_X_Value_r18_t	 x_value_r18;
	LPP_Y_Value_r18_t	 y_value_r18;
	LPP_Z_Value_r18_t	 z_value_r18;
	struct LPP_LocationUncertainty_r16	*locationUnc_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_RelativeCartesianLocation_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_cartesianCoordinatesUnits_r18_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_RelativeCartesianLocation_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_RelativeCartesianLocation_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_RelativeCartesianLocation_r18_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_RelativeCartesianLocation_r18_H_ */
#include <asn_internal.h>
