/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "LPP_NR-Cell-IDs-r17.h"

#include "LPP_NCGI-r15.h"
asn_TYPE_member_t asn_MBR_LPP_NR_Cell_IDs_r17_1[] = {
	{ ATF_POINTER, 3, offsetof(struct LPP_NR_Cell_IDs_r17, nr_CellGlobalID_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NCGI_r15,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-CellGlobalID-r17"
		},
	{ ATF_POINTER, 2, offsetof(struct LPP_NR_Cell_IDs_r17, nr_PhysCellID_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NR_PhysCellID_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-PhysCellID-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_NR_Cell_IDs_r17, nr_ARFCN_r17),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_ARFCN_ValueNR_r15,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-ARFCN-r17"
		},
};
static const int asn_MAP_LPP_NR_Cell_IDs_r17_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_LPP_NR_Cell_IDs_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_NR_Cell_IDs_r17_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nr-CellGlobalID-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nr-PhysCellID-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nr-ARFCN-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_Cell_IDs_r17_specs_1 = {
	sizeof(struct LPP_NR_Cell_IDs_r17),
	offsetof(struct LPP_NR_Cell_IDs_r17, _asn_ctx),
	asn_MAP_LPP_NR_Cell_IDs_r17_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LPP_NR_Cell_IDs_r17_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LPP_NR_Cell_IDs_r17 = {
	"NR-Cell-IDs-r17",
	"NR-Cell-IDs-r17",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_NR_Cell_IDs_r17_tags_1,
	sizeof(asn_DEF_LPP_NR_Cell_IDs_r17_tags_1)
		/sizeof(asn_DEF_LPP_NR_Cell_IDs_r17_tags_1[0]), /* 1 */
	asn_DEF_LPP_NR_Cell_IDs_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_NR_Cell_IDs_r17_tags_1)
		/sizeof(asn_DEF_LPP_NR_Cell_IDs_r17_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_NR_Cell_IDs_r17_1,
	3,	/* Elements count */
	&asn_SPC_LPP_NR_Cell_IDs_r17_specs_1	/* Additional specs */
};

