/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_LocationCoordinateTypes_H_
#define	_LPP_LocationCoordinateTypes_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_LocationCoordinateTypes */
typedef struct LPP_LocationCoordinateTypes {
	BOOLEAN_t	 ellipsoidPoint;
	BOOLEAN_t	 ellipsoidPointWithUncertaintyCircle;
	BOOLEAN_t	 ellipsoidPointWithUncertaintyEllipse;
	BOOLEAN_t	 polygon;
	BOOLEAN_t	 ellipsoidPointWithAltitude;
	BOOLEAN_t	 ellipsoidPointWithAltitudeAndUncertaintyEllipsoid;
	BOOLEAN_t	 ellipsoidArc;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_LocationCoordinateTypes__ext1 {
		BOOLEAN_t	*highAccuracyEllipsoidPointWithUncertaintyEllipse_r15;	/* OPTIONAL */
		BOOLEAN_t	*highAccuracyEllipsoidPointWithAltitudeAndUncertaintyEllipsoid_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_LocationCoordinateTypes__ext2 {
		BOOLEAN_t	*ha_EllipsoidPointWithScalableUncertaintyEllipse_r16;	/* OPTIONAL */
		BOOLEAN_t	*ha_EllipsoidPointWithAltitudeAndScalableUncertaintyEllipsoid_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_LocationCoordinateTypes__ext3 {
		BOOLEAN_t	*local2dPointWithUncertaintyEllipse_r18;	/* OPTIONAL */
		BOOLEAN_t	*local3dPointWithUncertaintyEllipsoid_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_LocationCoordinateTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_LocationCoordinateTypes;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_LocationCoordinateTypes_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_LocationCoordinateTypes_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_LocationCoordinateTypes_H_ */
#include <asn_internal.h>
