/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_TDOA_ProvideLocationInformation_r16_H_
#define	_LPP_NR_DL_TDOA_ProvideLocationInformation_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_NR_DL_TDOA_SignalMeasurementInformation_r16;
struct LPP_NR_DL_TDOA_LocationInformation_r16;
struct LPP_NR_DL_TDOA_Error_r16;

/* LPP_NR-DL-TDOA-ProvideLocationInformation-r16 */
typedef struct LPP_NR_DL_TDOA_ProvideLocationInformation_r16 {
	struct LPP_NR_DL_TDOA_SignalMeasurementInformation_r16	*nr_DL_TDOA_SignalMeasurementInformation_r16;	/* OPTIONAL */
	struct LPP_NR_DL_TDOA_LocationInformation_r16	*nr_dl_tdoa_LocationInformation_r16;	/* OPTIONAL */
	struct LPP_NR_DL_TDOA_Error_r16	*nr_DL_TDOA_Error_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_TDOA_ProvideLocationInformation_r16__ext1 {
		struct LPP_NR_DL_TDOA_ProvideLocationInformation_r16__ext1__nr_DL_TDOA_SignalMeasurementInstances_r17 {
			A_SEQUENCE_OF(struct LPP_NR_DL_TDOA_SignalMeasurementInformation_r16) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_DL_TDOA_SignalMeasurementInstances_r17;
		struct LPP_NR_DL_TDOA_ProvideLocationInformation_r16__ext1__nr_DL_TDOA_LocationInformationInstances_r17 {
			A_SEQUENCE_OF(struct LPP_NR_DL_TDOA_LocationInformation_r16) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_DL_TDOA_LocationInformationInstances_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_TDOA_ProvideLocationInformation_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_TDOA_ProvideLocationInformation_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_TDOA_ProvideLocationInformation_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_TDOA_ProvideLocationInformation_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_TDOA_ProvideLocationInformation_r16_H_ */
#include <asn_internal.h>
