/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "LPP_SSR-SatellitePCV-FrequencyElement-r18.h"

asn_TYPE_member_t asn_MBR_LPP_SSR_SatellitePCV_FrequencyElement_r18_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_SSR_SatellitePCV_FrequencyElement_r18, frequencyID_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_GNSS_FrequencyID_r15,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"frequencyID-r18"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_SSR_SatellitePCV_FrequencyElement_r18, phaseCenterVariations_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_SSR_PhaseCenterVariationList_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"phaseCenterVariations-r18"
		},
};
static const ber_tlv_tag_t asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_SSR_SatellitePCV_FrequencyElement_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* frequencyID-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* phaseCenterVariations-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_LPP_SSR_SatellitePCV_FrequencyElement_r18_specs_1 = {
	sizeof(struct LPP_SSR_SatellitePCV_FrequencyElement_r18),
	offsetof(struct LPP_SSR_SatellitePCV_FrequencyElement_r18, _asn_ctx),
	asn_MAP_LPP_SSR_SatellitePCV_FrequencyElement_r18_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18 = {
	"SSR-SatellitePCV-FrequencyElement-r18",
	"SSR-SatellitePCV-FrequencyElement-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1,
	sizeof(asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1)
		/sizeof(asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1[0]), /* 1 */
	asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1)
		/sizeof(asn_DEF_LPP_SSR_SatellitePCV_FrequencyElement_r18_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_SSR_SatellitePCV_FrequencyElement_r18_1,
	2,	/* Elements count */
	&asn_SPC_LPP_SSR_SatellitePCV_FrequencyElement_r18_specs_1	/* Additional specs */
};

