/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_SRS_CapabilityPerBand_r16_H_
#define	_LPP_SRS_CapabilityPerBand_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_FreqBandIndicatorNR-r16.h"
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18 {
	LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_supported	= 0
} e_LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18;
typedef enum LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18 {
	LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_supported	= 0
} e_LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18;
typedef enum LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18 {
	LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_supported	= 0
} e_LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18;
typedef enum LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18 {
	LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_supported	= 0
} e_LPP_SRS_CapabilityPerBand_r16__ext3__posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18;
typedef enum LPP_SRS_CapabilityPerBand_r16__ext3__dummy {
	LPP_SRS_CapabilityPerBand_r16__ext3__dummy_supported	= 0
} e_LPP_SRS_CapabilityPerBand_r16__ext3__dummy;

/* Forward declarations */
struct LPP_OLPC_SRS_Pos_r16;
struct LPP_SpatialRelationsSRS_Pos_r16;
struct LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17;
struct LPP_PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17;
struct LPP_PosSRS_SP_RRC_Inactive_InInitialUL_BWP_r17;
struct LPP_PosSRS_TxFrequencyHoppingRRC_Connected_r18;
struct LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18;
struct LPP_PosSRS_BWA_RRC_Inactive_r18;

/* LPP_SRS-CapabilityPerBand-r16 */
typedef struct LPP_SRS_CapabilityPerBand_r16 {
	LPP_FreqBandIndicatorNR_r16_t	 freqBandIndicatorNR_r16;
	struct LPP_OLPC_SRS_Pos_r16	*olpc_SRS_Pos_r16;	/* OPTIONAL */
	struct LPP_SpatialRelationsSRS_Pos_r16	*spatialRelationsSRS_Pos_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_SRS_CapabilityPerBand_r16__ext1 {
		struct LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17	*posSRS_RRC_Inactive_InInitialUL_BWP_r17;	/* OPTIONAL */
		struct LPP_PosSRS_RRC_Inactive_OutsideInitialUL_BWP_r17	*posSRS_RRC_Inactive_OutsideInitialUL_BWP_r17;	/* OPTIONAL */
		struct LPP_OLPC_SRS_Pos_r16	*olpc_SRS_PosRRC_Inactive_r17;	/* OPTIONAL */
		struct LPP_SpatialRelationsSRS_Pos_r16	*spatialRelationsSRS_PosRRC_Inactive_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_SRS_CapabilityPerBand_r16__ext2 {
		struct LPP_PosSRS_SP_RRC_Inactive_InInitialUL_BWP_r17	*posSRS_SP_RRC_Inactive_InInitialUL_BWP_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_SRS_CapabilityPerBand_r16__ext3 {
		long	*posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18;	/* OPTIONAL */
		long	*posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18;	/* OPTIONAL */
		long	*posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18;	/* OPTIONAL */
		long	*posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18;	/* OPTIONAL */
		struct LPP_PosSRS_TxFrequencyHoppingRRC_Connected_r18	*posSRS_TxFH_RRC_Connected_r18;	/* OPTIONAL */
		struct LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18	*posSRS_TxFH_RRC_Inactive_r18;	/* OPTIONAL */
		long	*dummy;	/* OPTIONAL */
		struct LPP_PosSRS_BWA_RRC_Inactive_r18	*posSRS_BWA_RRC_Inactive_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_SRS_CapabilityPerBand_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posSRS_Preconfigured_RRC_InactiveInitialUL_BWP_r18_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posSRS_Preconfigured_RRC_InactiveOutsideInitialUL_BWP_r18_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posSRS_ValidityAreaRRC_InactiveInitialUL_BWP_r18_18;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posSRS_ValidityAreaRRC_InactiveOutsideInitialUL_BWP_r18_20;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dummy_24;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_SRS_CapabilityPerBand_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_SRS_CapabilityPerBand_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_SRS_CapabilityPerBand_r16_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_SRS_CapabilityPerBand_r16_H_ */
#include <asn_internal.h>
