/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_ScheduledLocationTime_r17_H_
#define	_LPP_ScheduledLocationTime_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTCTime.h>
#include <NativeInteger.h>
#include "LPP_GNSS-ID.h"
#include <constr_SEQUENCE.h>
#include "LPP_ARFCN-ValueEUTRA.h"
#include "LPP_NR-PhysCellID-r16.h"
#include "LPP_ARFCN-ValueNR-r15.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_ScheduledLocationTime_r17__networkTime_r17_PR {
	LPP_ScheduledLocationTime_r17__networkTime_r17_PR_NOTHING,	/* No components present */
	LPP_ScheduledLocationTime_r17__networkTime_r17_PR_e_utraTime_r17,
	LPP_ScheduledLocationTime_r17__networkTime_r17_PR_nrTime_r17
	/* Extensions may appear below */
	
} LPP_ScheduledLocationTime_r17__networkTime_r17_PR;
typedef enum LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR {
	LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR_NOTHING,	/* No components present */
	LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR_scs15_r17,
	LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR_scs30_r17,
	LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR_scs60_r17,
	LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR_scs120_r17
} LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR;

/* Forward declarations */
struct LPP_CellGlobalIdEUTRA_AndUTRA;
struct LPP_NCGI_r15;

/* LPP_ScheduledLocationTime-r17 */
typedef struct LPP_ScheduledLocationTime_r17 {
	UTCTime_t	*utcTime_r17;	/* OPTIONAL */
	struct LPP_ScheduledLocationTime_r17__gnssTime_r17 {
		long	 gnss_TOD_msec_r17;
		LPP_GNSS_ID_t	 gnss_TimeID_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *gnssTime_r17;
	struct LPP_ScheduledLocationTime_r17__networkTime_r17 {
		LPP_ScheduledLocationTime_r17__networkTime_r17_PR present;
		union LPP_ScheduledLocationTime_r17__LPP_networkTime_r17_u {
			struct LPP_ScheduledLocationTime_r17__networkTime_r17__e_utraTime_r17 {
				long	 lte_PhysCellId_r17;
				LPP_ARFCN_ValueEUTRA_t	 lte_ArfcnEUTRA_r17;
				struct LPP_CellGlobalIdEUTRA_AndUTRA	*lte_CellGlobalId_r17;	/* OPTIONAL */
				long	 lte_SystemFrameNumber_r17;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *e_utraTime_r17;
			struct LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17 {
				LPP_NR_PhysCellID_r16_t	 nr_PhysCellID_r17;
				LPP_ARFCN_ValueNR_r15_t	 nr_ARFCN_r17;
				struct LPP_NCGI_r15	*nr_CellGlobalID_r17;	/* OPTIONAL */
				long	 nr_SFN_r17;
				struct LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17 {
					LPP_ScheduledLocationTime_r17__networkTime_r17__nrTime_r17__nr_Slot_r17_PR present;
					union LPP_ScheduledLocationTime_r17__LPP_networkTime_r17__LPP_nrTime_r17__LPP_nr_Slot_r17_u {
						long	 scs15_r17;
						long	 scs30_r17;
						long	 scs60_r17;
						long	 scs120_r17;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nr_Slot_r17;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nrTime_r17;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *networkTime_r17;
	long	*relativeTime_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_ScheduledLocationTime_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_ScheduledLocationTime_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_ScheduledLocationTime_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_ScheduledLocationTime_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ScheduledLocationTime_r17_H_ */
#include <asn_internal.h>
