/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_H_
#define	_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16 {
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_undefined	= 0,
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_assistance_data_missing	= 1,
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_unableToMeasureAnyTRP	= 2,
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_attemptedButUnableToMeasureSomeNeighbourTRPs	= 3,
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_thereWereNotEnoughSignalsReceivedForUeBasedDL_AoD	= 4,
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16_locationCalculationAssistanceDataMissing	= 5
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__cause_r16;
typedef enum LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__ext1__remoteUE_Indication_r18 {
	LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__ext1__remoteUE_Indication_r18_true	= 0
} e_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__ext1__remoteUE_Indication_r18;

/* LPP_NR-DL-AoD-TargetDeviceErrorCauses-r16 */
typedef struct LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16 {
	long	 cause_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16__ext1 {
		long	*remoteUE_Indication_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_cause_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_remoteUE_Indication_r18_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_AoD_TargetDeviceErrorCauses_r16_H_ */
#include <asn_internal.h>
