/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_SSR_URA_Set2_r17_H_
#define	_LPP_GNSS_SSR_URA_Set2_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "LPP_GNSS-SSR-URA-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_SSR_URA_Set2_r17__refEph_r17 {
	LPP_GNSS_SSR_URA_Set2_r17__refEph_r17_b1c	= 0
	/*
	 * Enumeration is extensible
	 */
} e_LPP_GNSS_SSR_URA_Set2_r17__refEph_r17;

/* LPP_GNSS-SSR-URA-Set2-r17 */
typedef struct LPP_GNSS_SSR_URA_Set2_r17 {
	long	 refEph_r17;
	LPP_GNSS_SSR_URA_r16_t	 gnss_SSR_URA_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_SSR_URA_Set2_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_refEph_r17_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_SSR_URA_Set2_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_SSR_URA_Set2_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_SSR_URA_Set2_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_SSR_URA_Set2_r17_H_ */
#include <asn_internal.h>
