/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_Multi_RTT_ProvideCapabilities_r16_H_
#define	_LPP_NR_Multi_RTT_ProvideCapabilities_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NR-DL-PRS-ResourcesCapability-r16.h"
#include "LPP_NR-Multi-RTT-MeasurementCapability-r16.h"
#include "LPP_NR-DL-PRS-QCL-ProcessingCapability-r16.h"
#include "LPP_NR-DL-PRS-ProcessingCapability-r16.h"
#include "LPP_NR-UL-SRS-Capability-r16.h"
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include "LPP_LOS-NLOS-IndicatorType2-r17.h"
#include "LPP_LOS-NLOS-IndicatorGranularity2-r17.h"
#include <constr_SEQUENCE.h>
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__additionalPathsReport_r16 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__additionalPathsReport_r16_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__additionalPathsReport_r16;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__periodicalReporting_r16 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__periodicalReporting_r16_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__periodicalReporting_r16;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17_eAoD	= 0,
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17_eAoA	= 1
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_UE_RxTx_TEG_ID_ReportingSupport_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_UE_RxTx_TEG_ID_ReportingSupport_r17_case1	= 0,
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_UE_RxTx_TEG_ID_ReportingSupport_r17_case2	= 1,
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_UE_RxTx_TEG_ID_ReportingSupport_r17_case3	= 2
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_UE_RxTx_TEG_ID_ReportingSupport_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n4	= 0,
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n6	= 1,
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n8	= 2
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17;
typedef enum LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext3__nr_MultiRTT_OnDemandPRS_ForBWA_Support_r18 {
	LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext3__nr_MultiRTT_OnDemandPRS_ForBWA_Support_r18_supported	= 0
} e_LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext3__nr_MultiRTT_OnDemandPRS_ForBWA_Support_r18;

/* Forward declarations */
struct LPP_NR_On_Demand_DL_PRS_Support_r17;
struct LPP_ScheduledLocationTimeSupport_r17;
struct LPP_PeriodicReportingIntervalMsSupport_r18;

/* LPP_NR-Multi-RTT-ProvideCapabilities-r16 */
typedef struct LPP_NR_Multi_RTT_ProvideCapabilities_r16 {
	LPP_NR_DL_PRS_ResourcesCapability_r16_t	 nr_Multi_RTT_PRS_Capability_r16;
	LPP_NR_Multi_RTT_MeasurementCapability_r16_t	 nr_Multi_RTT_MeasurementCapability_r16;
	LPP_NR_DL_PRS_QCL_ProcessingCapability_r16_t	 nr_DL_PRS_QCL_ProcessingCapability_r16;
	LPP_NR_DL_PRS_ProcessingCapability_r16_t	 nr_DL_PRS_ProcessingCapability_r16;
	LPP_NR_UL_SRS_Capability_r16_t	 nr_UL_SRS_Capability_r16;
	long	*additionalPathsReport_r16;	/* OPTIONAL */
	long	*periodicalReporting_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1 {
		long	*ten_ms_unit_ResponseTime_r17;	/* OPTIONAL */
		BIT_STRING_t	*nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17;	/* OPTIONAL */
		struct LPP_NR_On_Demand_DL_PRS_Support_r17	*nr_Multi_RTT_On_Demand_DL_PRS_Support_r17;	/* OPTIONAL */
		BIT_STRING_t	*nr_UE_RxTx_TEG_ID_ReportingSupport_r17;	/* OPTIONAL */
		struct LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_los_nlos_IndicatorSupport_r17 {
			LPP_LOS_NLOS_IndicatorType2_r17_t	 type_r17;
			LPP_LOS_NLOS_IndicatorGranularity2_r17_t	 granularity_r17;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_los_nlos_IndicatorSupport_r17;
		long	*additionalPathsExtSupport_r17;	/* OPTIONAL */
		struct LPP_ScheduledLocationTimeSupport_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		struct LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext1__nr_dl_prs_AssistanceDataValidity_r17 {
			long	*area_validity_r17;	/* OPTIONAL */
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_dl_prs_AssistanceDataValidity_r17;
		long	*multiMeasInSameMeasReport_r17;	/* OPTIONAL */
		long	*mg_ActivationRequest_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext2 {
		long	*posMeasGapSupport_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_NR_Multi_RTT_ProvideCapabilities_r16__ext3 {
		long	*nr_MultiRTT_OnDemandPRS_ForBWA_Support_r18;	/* OPTIONAL */
		struct LPP_PeriodicReportingIntervalMsSupport_r18	*periodicReportingIntervalMsSupport_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_Multi_RTT_ProvideCapabilities_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_additionalPathsReport_r16_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_periodicalReporting_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_ten_ms_unit_ResponseTime_r17_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_additionalPathsExtSupport_r17_27;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_multiMeasInSameMeasReport_r17_35;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_mg_ActivationRequest_r17_37;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posMeasGapSupport_r17_40;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_MultiRTT_OnDemandPRS_ForBWA_Support_r18_43;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_Multi_RTT_ProvideCapabilities_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_Multi_RTT_ProvideCapabilities_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_Multi_RTT_ProvideCapabilities_r16_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_Multi_RTT_ProvideCapabilities_r16_H_ */
#include <asn_internal.h>
