/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_H_
#define	_LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_NR-PhysCellID-r16.h"
#include "LPP_ARFCN-ValueNR-r15.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR {
	LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR_NOTHING,	/* No components present */
	LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR_perTrp_r17,
	LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR_perResource_r17
} LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR;

/* Forward declarations */
struct LPP_NCGI_r15;
struct LPP_LOS_NLOS_Indicator_r17;
struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerResource_r17;

/* LPP_NR-DL-PRS-ExpectedLOS-NLOS-AssistancePerTRP-r17 */
typedef struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17 {
	long	 dl_PRS_ID_r17;
	LPP_NR_PhysCellID_r16_t	*nr_PhysCellID_r17;	/* OPTIONAL */
	struct LPP_NCGI_r15	*nr_CellGlobalID_r17;	/* OPTIONAL */
	LPP_ARFCN_ValueNR_r15_t	*nr_ARFCN_r17;	/* OPTIONAL */
	struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17 {
		LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17_PR present;
		union LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__LPP_nr_los_nlos_indicator_r17_u {
			struct LPP_LOS_NLOS_Indicator_r17	*perTrp_r17;
			struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17__nr_los_nlos_indicator_r17__perResource_r17 {
				A_SEQUENCE_OF(struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerResource_r17) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *perResource_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nr_los_nlos_indicator_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_PRS_ExpectedLOS_NLOS_AssistancePerTRP_r17_H_ */
#include <asn_internal.h>
