/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_H_
#define	_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_FrequencyRangeReq_r17 {
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_FrequencyRangeReq_r17_fr1	= 0,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_FrequencyRangeReq_r17_fr2	= 1
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_FrequencyRangeReq_r17;
typedef enum LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17 {
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p4	= 0,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p5	= 1,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p8	= 2,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p10	= 3,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p16	= 4,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p20	= 5,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p32	= 6,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p40	= 7,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p64	= 8,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p80	= 9,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p160	= 10,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p320	= 11,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p640	= 12,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p1280	= 13,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p2560	= 14,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p5120	= 15,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p10240	= 16,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p20480	= 17,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p40960	= 18,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p81920	= 19,
	/*
	 * Enumeration is extensible
	 */
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p128_v1760	= 20,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p256_v1760	= 21,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17_p512_v1760	= 22
} e_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceSetPeriodicityReq_r17;
typedef enum LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17 {
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n2	= 0,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n4	= 1,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n6	= 2,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n8	= 3,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n16	= 4,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17_n32	= 5
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_ResourceRepetitionFactorReq_r17;
typedef enum LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17 {
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17_n2	= 0,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17_n4	= 1,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17_n6	= 2,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17_n12	= 3,
	/*
	 * Enumeration is extensible
	 */
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17_n1_v1800	= 4
} e_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_NumSymbolsReq_r17;
typedef enum LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17 {
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17_n2	= 0,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17_n4	= 1,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17_n6	= 2,
	LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17_n12	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17__dl_prs_CombSizeN_Req_r17;

/* Forward declarations */
struct LPP_DL_PRS_QCL_InformationReqTRPlist_r17;

/* LPP_NR-On-Demand-DL-PRS-PerFreqLayer-r17 */
typedef struct LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17 {
	long	 dl_prs_FrequencyRangeReq_r17;
	long	*dl_prs_ResourceSetPeriodicityReq_r17;	/* OPTIONAL */
	long	*dl_prs_ResourceBandwidthReq_r17;	/* OPTIONAL */
	long	*dl_prs_ResourceRepetitionFactorReq_r17;	/* OPTIONAL */
	long	*dl_prs_NumSymbolsReq_r17;	/* OPTIONAL */
	long	*dl_prs_CombSizeN_Req_r17;	/* OPTIONAL */
	struct LPP_DL_PRS_QCL_InformationReqTRPlist_r17	*dl_prs_QCL_InformationReqTRPlist_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_prs_FrequencyRangeReq_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_prs_ResourceSetPeriodicityReq_r17_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_prs_ResourceRepetitionFactorReq_r17_32;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_prs_NumSymbolsReq_r17_40;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_prs_CombSizeN_Req_r17_47;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_On_Demand_DL_PRS_PerFreqLayer_r17_H_ */
#include <asn_internal.h>
