/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_TDOA_MeasElement_r16_H_
#define	_LPP_NR_DL_TDOA_MeasElement_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_NR-PhysCellID-r16.h"
#include "LPP_ARFCN-ValueNR-r15.h"
#include "LPP_NR-DL-PRS-ResourceID-r16.h"
#include "LPP_NR-DL-PRS-ResourceSetID-r16.h"
#include "LPP_NR-TimeStamp-r16.h"
#include "LPP_NR-TimingQuality-r16.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR {
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_NOTHING,	/* No components present */
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k0_r16,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k1_r16,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k2_r16,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k3_r16,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k4_r16,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_k5_r16,
	/* Extensions may appear below */
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus6_r18,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus5_r18,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus4_r18,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus3_r18,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus2_r18,
	LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR_kMinus1_r18
} LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR;
typedef enum LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR {
	LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR_NOTHING,	/* No components present */
	LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR_perTRP_r17,
	LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR_perResource_r17
} LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR;
typedef enum LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_MeasBasedOnAggregatedResources_r18 {
	LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_MeasBasedOnAggregatedResources_r18_true	= 0
} e_LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_MeasBasedOnAggregatedResources_r18;
typedef enum LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18 {
	LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_singleHop	= 0,
	LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_multipleHop	= 1
} e_LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18;

/* Forward declarations */
struct LPP_NCGI_r15;
struct LPP_NR_AdditionalPathList_r16;
struct LPP_NR_DL_TDOA_AdditionalMeasurements_r16;
struct LPP_NR_AdditionalPathListExt_r17;
struct LPP_NR_DL_TDOA_AdditionalMeasurementsExt_r17;
struct LPP_LOS_NLOS_Indicator_r17;
struct LPP_NR_PhaseQuality_r18;
struct LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18;
struct LPP_NR_RSCPD_AdditionalMeasurementSamplesElement_r18;

/* LPP_NR-DL-TDOA-MeasElement-r16 */
typedef struct LPP_NR_DL_TDOA_MeasElement_r16 {
	long	 dl_PRS_ID_r16;
	LPP_NR_PhysCellID_r16_t	*nr_PhysCellID_r16;	/* OPTIONAL */
	struct LPP_NCGI_r15	*nr_CellGlobalID_r16;	/* OPTIONAL */
	LPP_ARFCN_ValueNR_r15_t	*nr_ARFCN_r16;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceID_r16_t	*nr_DL_PRS_ResourceID_r16;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceSetID_r16_t	*nr_DL_PRS_ResourceSetID_r16;	/* OPTIONAL */
	LPP_NR_TimeStamp_r16_t	 nr_TimeStamp_r16;
	struct LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16 {
		LPP_NR_DL_TDOA_MeasElement_r16__nr_RSTD_r16_PR present;
		union LPP_NR_DL_TDOA_MeasElement_r16__LPP_nr_RSTD_r16_u {
			long	 k0_r16;
			long	 k1_r16;
			long	 k2_r16;
			long	 k3_r16;
			long	 k4_r16;
			long	 k5_r16;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			long	 kMinus6_r18;
			long	 kMinus5_r18;
			long	 kMinus4_r18;
			long	 kMinus3_r18;
			long	 kMinus2_r18;
			long	 kMinus1_r18;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} nr_RSTD_r16;
	struct LPP_NR_AdditionalPathList_r16	*nr_AdditionalPathList_r16;	/* OPTIONAL */
	LPP_NR_TimingQuality_r16_t	 nr_TimingQuality_r16;
	long	*nr_DL_PRS_RSRP_Result_r16;	/* OPTIONAL */
	struct LPP_NR_DL_TDOA_AdditionalMeasurements_r16	*nr_DL_TDOA_AdditionalMeasurements_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_TDOA_MeasElement_r16__ext1 {
		long	*nr_UE_Rx_TEG_ID_r17;	/* OPTIONAL */
		long	*nr_DL_PRS_FirstPathRSRP_Result_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17 {
			LPP_NR_DL_TDOA_MeasElement_r16__ext1__nr_los_nlos_Indicator_r17_PR present;
			union LPP_NR_DL_TDOA_MeasElement_r16__LPP_ext1__LPP_nr_los_nlos_Indicator_r17_u {
				struct LPP_LOS_NLOS_Indicator_r17	*perTRP_r17;
				struct LPP_LOS_NLOS_Indicator_r17	*perResource_r17;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_los_nlos_Indicator_r17;
		struct LPP_NR_AdditionalPathListExt_r17	*nr_AdditionalPathListExt_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_AdditionalMeasurementsExt_r17	*nr_DL_TDOA_AdditionalMeasurementsExt_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_DL_TDOA_MeasElement_r16__ext2 {
		long	*nr_MeasBasedOnAggregatedResources_r18;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_AggregatedDL_PRS_ResourceInfo_List_r18 {
			A_SEQUENCE_OF(struct LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_AggregatedDL_PRS_ResourceInfo_List_r18;
		long	*nr_RSCPD_r18;	/* OPTIONAL */
		struct LPP_NR_PhaseQuality_r18	*nr_PhaseQuality_r18;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_MeasElement_r16__ext2__nr_RSCPD_AddMeasurementSamples_r18 {
			A_SEQUENCE_OF(struct LPP_NR_RSCPD_AdditionalMeasurementSamplesElement_r18) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_RSCPD_AddMeasurementSamples_r18;
		long	*nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_TDOA_MeasElement_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_MeasBasedOnAggregatedResources_r18_37;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_45;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_TDOA_MeasElement_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_TDOA_MeasElement_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_TDOA_MeasElement_r16_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_TDOA_MeasElement_r16_H_ */
#include <asn_internal.h>
