/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_WLAN_ProvideCapabilities_r13_H_
#define	_LPP_WLAN_ProvideCapabilities_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_WLAN_ProvideCapabilities_r13__wlan_Modes_r13 {
	LPP_WLAN_ProvideCapabilities_r13__wlan_Modes_r13_standalone	= 0,
	LPP_WLAN_ProvideCapabilities_r13__wlan_Modes_r13_ue_assisted	= 1,
	LPP_WLAN_ProvideCapabilities_r13__wlan_Modes_r13_ue_based	= 2
} e_LPP_WLAN_ProvideCapabilities_r13__wlan_Modes_r13;
typedef enum LPP_WLAN_ProvideCapabilities_r13__wlan_MeasSupported_r13 {
	LPP_WLAN_ProvideCapabilities_r13__wlan_MeasSupported_r13_rssi_r13	= 0,
	LPP_WLAN_ProvideCapabilities_r13__wlan_MeasSupported_r13_rtt_r13	= 1
} e_LPP_WLAN_ProvideCapabilities_r13__wlan_MeasSupported_r13;
typedef enum LPP_WLAN_ProvideCapabilities_r13__ext1__wlan_AP_AD_Supported_r14 {
	LPP_WLAN_ProvideCapabilities_r13__ext1__wlan_AP_AD_Supported_r14_ap_identifier	= 0,
	LPP_WLAN_ProvideCapabilities_r13__ext1__wlan_AP_AD_Supported_r14_ap_location	= 1
} e_LPP_WLAN_ProvideCapabilities_r13__ext1__wlan_AP_AD_Supported_r14;
typedef enum LPP_WLAN_ProvideCapabilities_r13__ext1__idleStateForMeasurements_r14 {
	LPP_WLAN_ProvideCapabilities_r13__ext1__idleStateForMeasurements_r14_required	= 0
} e_LPP_WLAN_ProvideCapabilities_r13__ext1__idleStateForMeasurements_r14;

/* Forward declarations */
struct LPP_PositioningModes;
struct LPP_ScheduledLocationTimeSupportPerMode_r17;
struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18;

/* LPP_WLAN-ProvideCapabilities-r13 */
typedef struct LPP_WLAN_ProvideCapabilities_r13 {
	BIT_STRING_t	 wlan_Modes_r13;
	BIT_STRING_t	 wlan_MeasSupported_r13;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_WLAN_ProvideCapabilities_r13__ext1 {
		BIT_STRING_t	*wlan_AP_AD_Supported_r14;	/* OPTIONAL */
		struct LPP_PositioningModes	*periodicalReportingSupported_r14;	/* OPTIONAL */
		long	*idleStateForMeasurements_r14;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_WLAN_ProvideCapabilities_r13__ext2 {
		struct LPP_ScheduledLocationTimeSupportPerMode_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_WLAN_ProvideCapabilities_r13__ext3 {
		struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18	*periodicReportingIntervalMsSupport_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_WLAN_ProvideCapabilities_r13_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_idleStateForMeasurements_r14_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_WLAN_ProvideCapabilities_r13;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_WLAN_ProvideCapabilities_r13_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_WLAN_ProvideCapabilities_r13_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_WLAN_ProvideCapabilities_r13_H_ */
#include <asn_internal.h>
