/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_On_Demand_DL_PRS_Configurations_r17_H_
#define	_LPP_NR_On_Demand_DL_PRS_Configurations_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_On_Demand_DL_PRS_Configuration_r17;
struct LPP_OnDemandDL_PRS_AggregationInfo_r18;

/* LPP_NR-On-Demand-DL-PRS-Configurations-r17 */
typedef struct LPP_NR_On_Demand_DL_PRS_Configurations_r17 {
	struct LPP_NR_On_Demand_DL_PRS_Configurations_r17__on_demand_dl_prs_configuration_list_r17 {
		A_SEQUENCE_OF(struct LPP_On_Demand_DL_PRS_Configuration_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} on_demand_dl_prs_configuration_list_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_On_Demand_DL_PRS_Configurations_r17__ext1 {
		struct LPP_NR_On_Demand_DL_PRS_Configurations_r17__ext1__onDemandDL_PRS_AggregationList_r18 {
			A_SEQUENCE_OF(struct LPP_OnDemandDL_PRS_AggregationInfo_r18) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *onDemandDL_PRS_AggregationList_r18;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_On_Demand_DL_PRS_Configurations_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_On_Demand_DL_PRS_Configurations_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_On_Demand_DL_PRS_Configurations_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_On_Demand_DL_PRS_Configurations_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_On_Demand_DL_PRS_Configurations_r17_H_ */
#include <asn_internal.h>
