/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_AoD_ReportConfig_r16_H_
#define	_LPP_NR_DL_AoD_ReportConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "LPP_LOS-NLOS-IndicatorType1-r17.h"
#include "LPP_LOS-NLOS-IndicatorGranularity1-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_AoD_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17 {
	LPP_NR_DL_AoD_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17_requested	= 0
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_DL_AoD_ReportConfig_r16__ext1__reducedDL_PRS_ProcessingSamples_r17;
typedef enum LPP_NR_DL_AoD_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17 {
	LPP_NR_DL_AoD_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17_requested	= 0
} e_LPP_NR_DL_AoD_ReportConfig_r16__ext1__lowerRxBeamSweepingFactor_FR2_r17;

/* Forward declarations */
struct LPP_NR_DL_PRS_MeasurementTimeWindowsConfig_r18;

/* LPP_NR-DL-AoD-ReportConfig-r16 */
typedef struct LPP_NR_DL_AoD_ReportConfig_r16 {
	long	*maxDL_PRS_RSRP_MeasurementsPerTRP_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_AoD_ReportConfig_r16__ext1 {
		long	*maxDL_PRS_RSRP_MeasurementsPerTRP_r17;	/* OPTIONAL */
		long	*maxDL_PRS_RSRPP_MeasurementsPerTRP_r17;	/* OPTIONAL */
		struct LPP_NR_DL_AoD_ReportConfig_r16__ext1__nr_los_nlos_IndicatorRequest_r17 {
			LPP_LOS_NLOS_IndicatorType1_r17_t	 type_r17;
			LPP_LOS_NLOS_IndicatorGranularity1_r17_t	 granularity_r17;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_los_nlos_IndicatorRequest_r17;
		long	*reducedDL_PRS_ProcessingSamples_r17;	/* OPTIONAL */
		long	*lowerRxBeamSweepingFactor_FR2_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_DL_AoD_ReportConfig_r16__ext2 {
		struct LPP_NR_DL_PRS_MeasurementTimeWindowsConfig_r18	*nr_DL_PRS_MeasurementTimeWindowsConfig_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_AoD_ReportConfig_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_reducedDL_PRS_ProcessingSamples_r17_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_lowerRxBeamSweepingFactor_FR2_r17_14;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_AoD_ReportConfig_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_AoD_ReportConfig_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_AoD_ReportConfig_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_AoD_ReportConfig_r16_H_ */
#include <asn_internal.h>
