/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_ArrayOfGridPoints_r18_H_
#define	_LPP_ArrayOfGridPoints_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_SpatialDelta-r18.h"
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR {
	LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR_NOTHING,	/* No components present */
	LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR_bog16_r18,
	LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR_bog64_r18,
	LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR_bog256_r18
	/* Extensions may appear below */
	
} LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR;

/* LPP_ArrayOfGridPoints-r18 */
typedef struct LPP_ArrayOfGridPoints_r18 {
	long	 referencePointLatitude_r18;
	long	 referencePointLongitude_r18;
	long	 numberOfStepsSouth_r18;
	long	 numberOfStepsEast_r18;
	LPP_SpatialDelta_r18_t	 stepSouth_r18;
	LPP_SpatialDelta_r18_t	 stepEast_r18;
	struct LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18 {
		LPP_ArrayOfGridPoints_r18__bitmaskOfGrids_r18_PR present;
		union LPP_ArrayOfGridPoints_r18__LPP_bitmaskOfGrids_r18_u {
			BIT_STRING_t	 bog16_r18;
			BIT_STRING_t	 bog64_r18;
			BIT_STRING_t	 bog256_r18;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *bitmaskOfGrids_r18;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_ArrayOfGridPoints_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_ArrayOfGridPoints_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_ArrayOfGridPoints_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_ArrayOfGridPoints_r18_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ArrayOfGridPoints_r18_H_ */
#include <asn_internal.h>
