/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_RxTxTEG_TimingErrorMargin_r17_H_
#define	_LPP_RxTxTEG_TimingErrorMargin_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_RxTxTEG_TimingErrorMargin_r17 {
	LPP_RxTxTEG_TimingErrorMargin_r17_tc0_5	= 0,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc1	= 1,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc2	= 2,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc4	= 3,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc8	= 4,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc12	= 5,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc16	= 6,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc20	= 7,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc24	= 8,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc32	= 9,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc40	= 10,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc48	= 11,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc64	= 12,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc80	= 13,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc96	= 14,
	LPP_RxTxTEG_TimingErrorMargin_r17_tc128	= 15
} e_LPP_RxTxTEG_TimingErrorMargin_r17;

/* LPP_RxTxTEG-TimingErrorMargin-r17 */
typedef long	 LPP_RxTxTEG_TimingErrorMargin_r17_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LPP_RxTxTEG_TimingErrorMargin_r17_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LPP_RxTxTEG_TimingErrorMargin_r17;
extern const asn_INTEGER_specifics_t asn_SPC_LPP_RxTxTEG_TimingErrorMargin_r17_specs_1;
asn_struct_free_f LPP_RxTxTEG_TimingErrorMargin_r17_free;
asn_struct_print_f LPP_RxTxTEG_TimingErrorMargin_r17_print;
asn_constr_check_f LPP_RxTxTEG_TimingErrorMargin_r17_constraint;
ber_type_decoder_f LPP_RxTxTEG_TimingErrorMargin_r17_decode_ber;
der_type_encoder_f LPP_RxTxTEG_TimingErrorMargin_r17_encode_der;
xer_type_decoder_f LPP_RxTxTEG_TimingErrorMargin_r17_decode_xer;
xer_type_encoder_f LPP_RxTxTEG_TimingErrorMargin_r17_encode_xer;
jer_type_encoder_f LPP_RxTxTEG_TimingErrorMargin_r17_encode_jer;
per_type_decoder_f LPP_RxTxTEG_TimingErrorMargin_r17_decode_uper;
per_type_encoder_f LPP_RxTxTEG_TimingErrorMargin_r17_encode_uper;
per_type_decoder_f LPP_RxTxTEG_TimingErrorMargin_r17_decode_aper;
per_type_encoder_f LPP_RxTxTEG_TimingErrorMargin_r17_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_RxTxTEG_TimingErrorMargin_r17_H_ */
#include <asn_internal.h>
