/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_BT_AntArrayConfig_r18_H_
#define	_LPP_BT_AntArrayConfig_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_BT_AntArrayConfig_r18_PR {
	LPP_BT_AntArrayConfig_r18_PR_NOTHING,	/* No components present */
	LPP_BT_AntArrayConfig_r18_PR_bt_UniformLinearArray_r18,
	LPP_BT_AntArrayConfig_r18_PR_bt_UniformRectangularArray_r18,
	LPP_BT_AntArrayConfig_r18_PR_bt_UniformCircularArray_r18,
	LPP_BT_AntArrayConfig_r18_PR_bt_GenericArray_r18
} LPP_BT_AntArrayConfig_r18_PR;

/* Forward declarations */
struct LPP_BT_UniformLinearArray_r18;
struct LPP_BT_UniformRectangularArray_r18;
struct LPP_BT_UniformCircularArray_r18;
struct LPP_BT_GenericArray_r18;

/* LPP_BT-AntArrayConfig-r18 */
typedef struct LPP_BT_AntArrayConfig_r18 {
	LPP_BT_AntArrayConfig_r18_PR present;
	union LPP_BT_AntArrayConfig_r18_u {
		struct LPP_BT_UniformLinearArray_r18	*bt_UniformLinearArray_r18;
		struct LPP_BT_UniformRectangularArray_r18	*bt_UniformRectangularArray_r18;
		struct LPP_BT_UniformCircularArray_r18	*bt_UniformCircularArray_r18;
		struct LPP_BT_GenericArray_r18	*bt_GenericArray_r18;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_BT_AntArrayConfig_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_BT_AntArrayConfig_r18;
extern asn_CHOICE_specifics_t asn_SPC_LPP_BT_AntArrayConfig_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_BT_AntArrayConfig_r18_1[4];
extern asn_per_constraints_t asn_PER_type_LPP_BT_AntArrayConfig_r18_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_BT_AntArrayConfig_r18_H_ */
#include <asn_internal.h>
