/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_H_
#define	_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n4	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n8	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n12	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17_n16	= 5
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfSRSposResourceSets_r17;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n4	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n8	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n16	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n32	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_n64	= 6
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResources_r17;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n3	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n4	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n5	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n6	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n8	= 6,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n10	= 7,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n12	= 8,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_n14	= 9
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n4	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n8	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n16	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n32	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17_n64	= 6
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResources_r17;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n3	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n4	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n5	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n6	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n8	= 6,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n10	= 7,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n12	= 8,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17_n14	= 9
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__maxNumOfPeriodicSRSposResourcesPerSlot_r17;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n4	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n8	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n16	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n32	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1_n64	= 6
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy1;
typedef enum LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2 {
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n1	= 0,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n2	= 1,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n3	= 2,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n4	= 3,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n5	= 4,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n6	= 5,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n8	= 6,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n10	= 7,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n12	= 8,
	LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2_n14	= 9
} e_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17__dummy2;

/* LPP_PosSRS-RRC-Inactive-InInitialUL-BWP-r17 */
typedef struct LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17 {
	long	*maxNumOfSRSposResourceSets_r17;	/* OPTIONAL */
	long	*maxNumOfPeriodicAndSemiPersistentSRSposResources_r17;	/* OPTIONAL */
	long	*maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17;	/* OPTIONAL */
	long	*maxNumOfPeriodicSRSposResources_r17;	/* OPTIONAL */
	long	*maxNumOfPeriodicSRSposResourcesPerSlot_r17;	/* OPTIONAL */
	long	*dummy1;	/* OPTIONAL */
	long	*dummy2;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxNumOfSRSposResourceSets_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxNumOfPeriodicAndSemiPersistentSRSposResources_r17_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxNumOfPeriodicAndSemiPersistentSRSposResourcesPerSlot_r17_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxNumOfPeriodicSRSposResources_r17_28;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxNumOfPeriodicSRSposResourcesPerSlot_r17_36;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dummy1_47;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dummy2_55;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_PosSRS_RRC_Inactive_InInitialUL_BWP_r17_H_ */
#include <asn_internal.h>
