/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_H_
#define	_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR {
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR_NOTHING,	/* No components present */
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR_inside_r18,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR_outside_r18
} LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR;
typedef enum LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18 {
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18_upper_left	= 0,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18_upper_right	= 1,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18_lower_left	= 2,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18_lower_right	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__inside_r18;
typedef enum LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18 {
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_north	= 0,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_west	= 1,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_south	= 2,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_east	= 3,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_above	= 4,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18_below	= 5
	/*
	 * Enumeration is extensible
	 */
} e_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18__outside_r18;
typedef enum LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__verticalGridType_r18 {
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__verticalGridType_r18_ground_level	= 0,
	LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__verticalGridType_r18_threeD	= 1
} e_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__verticalGridType_r18;

/* LPP_GNSS-LOS-NLOS-GriddedIndicationsReq-r18 */
typedef struct LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18 {
	long	*gridPointsSetID_Req_r18;	/* OPTIONAL */
	struct LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18 {
		LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__relativeLocationInfo_r18_PR present;
		union LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18__LPP_relativeLocationInfo_r18_u {
			long	 inside_r18;
			long	 outside_r18;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *relativeLocationInfo_r18;
	long	 verticalGridType_r18;
	long	*referenceAltitudeFine_r18;	/* OPTIONAL */
	long	*referenceAltitudeCoarse_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_inside_r18_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_outside_r18_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_verticalGridType_r18_18;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_LOS_NLOS_GriddedIndicationsReq_r18_H_ */
#include <asn_internal.h>
