/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_TRP_IntegrityServiceAlertElement_r18_H_
#define	_LPP_NR_TRP_IntegrityServiceAlertElement_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_NR-PhysCellID-r16.h"
#include "LPP_ARFCN-ValueNR-r15.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_NCGI_r15;

/* LPP_NR-TRP-IntegrityServiceAlertElement-r18 */
typedef struct LPP_NR_TRP_IntegrityServiceAlertElement_r18 {
	long	 dl_PRS_ID_r18;
	LPP_NR_PhysCellID_r16_t	*nr_PhysCellID_r18;	/* OPTIONAL */
	struct LPP_NCGI_r15	*nr_CellGlobalID_r18;	/* OPTIONAL */
	LPP_ARFCN_ValueNR_r15_t	*nr_ARFCN_r18;	/* OPTIONAL */
	BOOLEAN_t	*rtd_DoNotUse_r18;	/* OPTIONAL */
	BOOLEAN_t	*trp_LocationDoNotUse_r18;	/* OPTIONAL */
	BOOLEAN_t	*beamInfo_DoNotUse_r18;	/* OPTIONAL */
	BOOLEAN_t	*beamAntennaInfo_DoNotUse_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_TRP_IntegrityServiceAlertElement_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_TRP_IntegrityServiceAlertElement_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_TRP_IntegrityServiceAlertElement_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_TRP_IntegrityServiceAlertElement_r18_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_TRP_IntegrityServiceAlertElement_r18_H_ */
#include <asn_internal.h>
