/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_DL_AoD_MeasCapabilityPerBand_r16_H_
#define	_LPP_DL_AoD_MeasCapabilityPerBand_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_FreqBandIndicatorNR-r16.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16_supported	= 0
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_DL_TDOA_r16;
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16_supported	= 0
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__simul_NR_DL_AoD_Multi_RTT_r16;
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n1	= 0,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n2	= 1,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n4	= 2,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n8	= 3,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n16	= 4,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_n24	= 5
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17;
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17_supported	= 0
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1__dl_PRS_MeasRRC_Inactive_r17;
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfMeasurementsInTimeWindow_r18 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfMeasurementsInTimeWindow_r18_rsrp	= 0,
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfMeasurementsInTimeWindow_r18_rsrpp	= 1
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfMeasurementsInTimeWindow_r18;
typedef enum LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfPRS_MeasurementRRC_Idle_r18 {
	LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfPRS_MeasurementRRC_Idle_r18_supported	= 0
} e_LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2__supportOfPRS_MeasurementRRC_Idle_r18;

/* LPP_DL-AoD-MeasCapabilityPerBand-r16 */
typedef struct LPP_DL_AoD_MeasCapabilityPerBand_r16 {
	LPP_FreqBandIndicatorNR_r16_t	 freqBandIndicatorNR_r16;
	long	*simul_NR_DL_AoD_DL_TDOA_r16;	/* OPTIONAL */
	long	*simul_NR_DL_AoD_Multi_RTT_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_DL_AoD_MeasCapabilityPerBand_r16__ext1 {
		long	*maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17;	/* OPTIONAL */
		long	*dl_PRS_MeasRRC_Inactive_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_DL_AoD_MeasCapabilityPerBand_r16__ext2 {
		BIT_STRING_t	*supportOfMeasurementsInTimeWindow_r18;	/* OPTIONAL */
		long	*supportOfPRS_MeasurementRRC_Idle_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_DL_AoD_MeasCapabilityPerBand_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_simul_NR_DL_AoD_DL_TDOA_r16_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_simul_NR_DL_AoD_Multi_RTT_r16_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maxDL_PRS_FirstPathRSRP_MeasPerTRP_r17_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_dl_PRS_MeasRRC_Inactive_r17_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfPRS_MeasurementRRC_Idle_r18_22;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_DL_AoD_MeasCapabilityPerBand_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_DL_AoD_MeasCapabilityPerBand_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_DL_AoD_MeasCapabilityPerBand_r16_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_DL_AoD_MeasCapabilityPerBand_r16_H_ */
#include <asn_internal.h>
