/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_TDOA_MeasurementCapability_r16_H_
#define	_LPP_NR_DL_TDOA_MeasurementCapability_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR1_r16 {
	LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR1_r16_supported	= 0
} e_LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR1_r16;
typedef enum LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR2_r16 {
	LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR2_r16_supported	= 0
} e_LPP_NR_DL_TDOA_MeasurementCapability_r16__supportOfDL_PRS_RSRP_MeasFR2_r16;

/* Forward declarations */
struct LPP_NR_UE_TEG_Capability_r17;
struct LPP_DL_TDOA_MeasCapabilityPerBand_r17;

/* LPP_NR-DL-TDOA-MeasurementCapability-r16 */
typedef struct LPP_NR_DL_TDOA_MeasurementCapability_r16 {
	long	 dl_RSTD_MeasurementPerPairOfTRP_FR1_r16;
	long	 dl_RSTD_MeasurementPerPairOfTRP_FR2_r16;
	long	*supportOfDL_PRS_RSRP_MeasFR1_r16;	/* OPTIONAL */
	long	*supportOfDL_PRS_RSRP_MeasFR2_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_TDOA_MeasurementCapability_r16__ext1 {
		struct LPP_NR_UE_TEG_Capability_r17	*nr_UE_TEG_Capability_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_MeasurementCapability_r16__ext1__dl_tdoa_MeasCapabilityBandList_r17 {
			A_SEQUENCE_OF(struct LPP_DL_TDOA_MeasCapabilityPerBand_r17) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *dl_tdoa_MeasCapabilityBandList_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_TDOA_MeasurementCapability_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfDL_PRS_RSRP_MeasFR1_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_supportOfDL_PRS_RSRP_MeasFR2_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_TDOA_MeasurementCapability_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_TDOA_MeasurementCapability_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_TDOA_MeasurementCapability_r16_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_TDOA_MeasurementCapability_r16_H_ */
#include <asn_internal.h>
