/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_SSR_IOD_UpdateReq_r18_H_
#define	_LPP_GNSS_SSR_IOD_UpdateReq_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_GNSS-SSR-IOD-UpdateReq-r18 */
typedef struct LPP_GNSS_SSR_IOD_UpdateReq_r18 {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_SSR_IOD_UpdateReq_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_SSR_IOD_UpdateReq_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_SSR_IOD_UpdateReq_r18_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_SSR_IOD_UpdateReq_r18_H_ */
#include <asn_internal.h>
