/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_PeriodicalReportingCriteriaExt_r18_H_
#define	_LPP_PeriodicalReportingCriteriaExt_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18 {
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra2	= 0,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra4	= 1,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra8	= 2,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra16	= 3,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra32	= 4,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra64	= 5,
	LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18_ra_Infinity	= 6
} e_LPP_PeriodicalReportingCriteriaExt_r18__reportingAmount_r18;

/* LPP_PeriodicalReportingCriteriaExt-r18 */
typedef struct LPP_PeriodicalReportingCriteriaExt_r18 {
	long	*reportingAmount_r18;	/* DEFAULT 6 */
	long	 reportingIntervalMs_r18;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_PeriodicalReportingCriteriaExt_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_reportingAmount_r18_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_PeriodicalReportingCriteriaExt_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_PeriodicalReportingCriteriaExt_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_PeriodicalReportingCriteriaExt_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_PeriodicalReportingCriteriaExt_r18_H_ */
#include <asn_internal.h>
