/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_H_
#define	_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR {
	LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR_NOTHING,	/* No components present */
	LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR_expectedAoD_r17,
	LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR_expectedAoA_r17
} LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR;

/* LPP_NR-DL-PRS-ExpectedAoD-or-AoA-r17 */
typedef struct LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17 {
	LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_PR present;
	union LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_u {
		struct LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17__expectedAoD_r17 {
			long	 expectedDL_AzimuthAoD_r17;
			long	*expectedDL_AzimuthAoD_Unc_r17;	/* OPTIONAL */
			long	 expectedDL_ZenithAoD_r17;
			long	*expectedDL_ZenithAoD_Unc_r17;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *expectedAoD_r17;
		struct LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17__expectedAoA_r17 {
			long	 expectedDL_AzimuthAoA_r17;
			long	*expectedDL_AzimuthAoA_Unc_r17;	/* OPTIONAL */
			long	 expectedDL_ZenithAoA_r17;
			long	*expectedDL_ZenithAoA_Unc_r17;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *expectedAoA_r17;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17;
extern asn_CHOICE_specifics_t asn_SPC_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_1[2];
extern asn_per_constraints_t asn_PER_type_LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_PRS_ExpectedAoD_or_AoA_r17_H_ */
#include <asn_internal.h>
