/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_H_
#define	_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NR-Multi-RTT-MeasList-r16.h"
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include "LPP_TEG-TimingErrorMargin-r17.h"
#include "LPP_RxTxTEG-TimingErrorMargin-r17.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16 {
	LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16_nTA1	= 0,
	LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16_nTA2	= 1,
	LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16_nTA3	= 2,
	LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16_nTA4	= 3
	/*
	 * Enumeration is extensible
	 */
} e_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__nr_NTA_Offset_r16;

/* Forward declarations */
struct LPP_NR_SRS_TxTEG_Element_r17;

/* LPP_NR-Multi-RTT-SignalMeasurementInformation-r16 */
typedef struct LPP_NR_Multi_RTT_SignalMeasurementInformation_r16 {
	LPP_NR_Multi_RTT_MeasList_r16_t	 nr_Multi_RTT_MeasList_r16;
	long	*nr_NTA_Offset_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__ext1 {
		struct LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__ext1__nr_SRS_TxTEG_Set_r17 {
			A_SEQUENCE_OF(struct LPP_NR_SRS_TxTEG_Element_r17) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_SRS_TxTEG_Set_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_Multi_RTT_SignalMeasurementInformation_r16__ext2 {
		LPP_TEG_TimingErrorMargin_r17_t	*nr_UE_RxTEG_TimingErrorMargin_r17;	/* OPTIONAL */
		LPP_TEG_TimingErrorMargin_r17_t	*nr_UE_TxTEG_TimingErrorMargin_r17;	/* OPTIONAL */
		LPP_RxTxTEG_TimingErrorMargin_r17_t	*nr_UE_RxTxTEG_TimingErrorMargin_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_NTA_Offset_r16_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_Multi_RTT_SignalMeasurementInformation_r16_H_ */
#include <asn_internal.h>
