/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_BT_AoA_Config_r18_H_
#define	_LPP_BT_AoA_Config_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_BT_AoA_Config_r18__cte_Status_r18 {
	LPP_BT_AoA_Config_r18__cte_Status_r18_enabled	= 0
} e_LPP_BT_AoA_Config_r18__cte_Status_r18;
typedef enum LPP_BT_AoA_Config_r18__tx_PHY_M2_r18 {
	LPP_BT_AoA_Config_r18__tx_PHY_M2_r18_m2	= 0
} e_LPP_BT_AoA_Config_r18__tx_PHY_M2_r18;

/* LPP_BT-AoA-Config-r18 */
typedef struct LPP_BT_AoA_Config_r18 {
	BIT_STRING_t	 bt_Addr_r18;
	long	*cte_Status_r18;	/* OPTIONAL */
	long	*primaryAdvInterval_r18;	/* OPTIONAL */
	long	*secondAdvInterval_r18;	/* OPTIONAL */
	long	*tx_Power_r18;	/* OPTIONAL */
	long	*cte_Length_r18;	/* OPTIONAL */
	long	*cte_Count_r18;	/* OPTIONAL */
	long	*tx_PHY_M2_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_BT_AoA_Config_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_cte_Status_r18_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_tx_PHY_M2_r18_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_BT_AoA_Config_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_BT_AoA_Config_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_BT_AoA_Config_r18_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_BT_AoA_Config_r18_H_ */
#include <asn_internal.h>
