/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_UE_RxTx_TEG_Info_r17_H_
#define	_LPP_NR_UE_RxTx_TEG_Info_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_UE_RxTx_TEG_Info_r17_PR {
	LPP_NR_UE_RxTx_TEG_Info_r17_PR_NOTHING,	/* No components present */
	LPP_NR_UE_RxTx_TEG_Info_r17_PR_case1_r17,
	LPP_NR_UE_RxTx_TEG_Info_r17_PR_case2_r17,
	LPP_NR_UE_RxTx_TEG_Info_r17_PR_case3_r17
	/* Extensions may appear below */
	
} LPP_NR_UE_RxTx_TEG_Info_r17_PR;

/* LPP_NR-UE-RxTx-TEG-Info-r17 */
typedef struct LPP_NR_UE_RxTx_TEG_Info_r17 {
	LPP_NR_UE_RxTx_TEG_Info_r17_PR present;
	union LPP_NR_UE_RxTx_TEG_Info_r17_u {
		struct LPP_NR_UE_RxTx_TEG_Info_r17__case1_r17 {
			long	 nr_UE_RxTx_TEG_ID_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *case1_r17;
		struct LPP_NR_UE_RxTx_TEG_Info_r17__case2_r17 {
			long	 nr_UE_RxTx_TEG_ID_r17;
			long	 nr_UE_Tx_TEG_Index_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *case2_r17;
		struct LPP_NR_UE_RxTx_TEG_Info_r17__case3_r17 {
			long	 nr_UE_Rx_TEG_ID_r17;
			long	 nr_UE_Tx_TEG_Index_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *case3_r17;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_UE_RxTx_TEG_Info_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_UE_RxTx_TEG_Info_r17;
extern asn_CHOICE_specifics_t asn_SPC_LPP_NR_UE_RxTx_TEG_Info_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_UE_RxTx_TEG_Info_r17_1[3];
extern asn_per_constraints_t asn_PER_type_LPP_NR_UE_RxTx_TEG_Info_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_UE_RxTx_TEG_Info_r17_H_ */
#include <asn_internal.h>
