/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_AoD_RequestLocationInformation_r16_H_
#define	_LPP_NR_DL_AoD_RequestLocationInformation_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "LPP_NR-DL-AoD-ReportConfig-r16.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_AoD_RequestLocationInformation_r16__ext1__multiMeasInSameReport_r17 {
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext1__multiMeasInSameReport_r17_requested	= 0
} e_LPP_NR_DL_AoD_RequestLocationInformation_r16__ext1__multiMeasInSameReport_r17;
typedef enum LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR {
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR_NOTHING,	/* No components present */
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR_fr1,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR_fr2
} LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR;
typedef enum LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1 {
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1_mhz40	= 0,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1_mhz50	= 1,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1_mhz80	= 2,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1_mhz100	= 3
} e_LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr1;
typedef enum LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr2 {
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr2_mhz100	= 0,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr2_mhz200	= 1,
	LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr2_mhz400	= 2
} e_LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18__fr2;

/* LPP_NR-DL-AoD-RequestLocationInformation-r16 */
typedef struct LPP_NR_DL_AoD_RequestLocationInformation_r16 {
	BOOLEAN_t	 nr_AssistanceAvailability_r16;
	LPP_NR_DL_AoD_ReportConfig_r16_t	 nr_DL_AoD_ReportConfig_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_AoD_RequestLocationInformation_r16__ext1 {
		long	*multiMeasInSameReport_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2 {
		struct LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18 {
			struct LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18 {
				LPP_NR_DL_AoD_RequestLocationInformation_r16__ext2__nr_DL_PRS_RxHoppingRequest_r18__nr_DL_PRS_RxHoppingTotalBandwidth_r18_PR present;
				union LPP_NR_DL_AoD_RequestLocationInformation_r16__LPP_ext2__LPP_nr_DL_PRS_RxHoppingRequest_r18__LPP_nr_DL_PRS_RxHoppingTotalBandwidth_r18_u {
					long	 fr1;
					long	 fr2;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nr_DL_PRS_RxHoppingTotalBandwidth_r18;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_DL_PRS_RxHoppingRequest_r18;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_AoD_RequestLocationInformation_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_multiMeasInSameReport_r17_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_fr1_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_fr2_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_AoD_RequestLocationInformation_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_AoD_RequestLocationInformation_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_AoD_RequestLocationInformation_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_AoD_RequestLocationInformation_r16_H_ */
#include <asn_internal.h>
