/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_AlmanacNavIC_AlmanacSet_r16_H_
#define	_LPP_AlmanacNavIC_AlmanacSet_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_SV-ID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_AlmanacNavIC-AlmanacSet-r16 */
typedef struct LPP_AlmanacNavIC_AlmanacSet_r16 {
	LPP_SV_ID_t	 svID_r16;
	long	*navic_AlmToa_r16;	/* OPTIONAL */
	long	 navic_AlmE_r16;
	long	 navic_AlmOMEGADOT_r16;
	long	 navic_AlmSqrtA_r16;
	long	 navic_AlmOMEGAo_r16;
	long	 navic_AlmOmega_r16;
	long	 navic_AlmMo_r16;
	long	 navic_Almaf0_r16;
	long	 navic_Almaf1_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_AlmanacNavIC_AlmanacSet_r16__ext1 {
		long	*navicL5_i0_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_AlmanacNavIC_AlmanacSet_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_AlmanacNavIC_AlmanacSet_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_AlmanacNavIC_AlmanacSet_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_AlmanacNavIC_AlmanacSet_r16_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_AlmanacNavIC_AlmanacSet_r16_H_ */
#include <asn_internal.h>
