/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_SSR_CodeBiasReq_r15_H_
#define	_LPP_GNSS_SSR_CodeBiasReq_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_GNSS-SignalIDs.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_SSR_CodeBiasReq_r15__ext1__ssr_IntegrityCodeBiasBoundsReq_r17 {
	LPP_GNSS_SSR_CodeBiasReq_r15__ext1__ssr_IntegrityCodeBiasBoundsReq_r17_requested	= 0
} e_LPP_GNSS_SSR_CodeBiasReq_r15__ext1__ssr_IntegrityCodeBiasBoundsReq_r17;

/* Forward declarations */
struct LPP_GNSS_NavListInfo_r15;

/* LPP_GNSS-SSR-CodeBiasReq-r15 */
typedef struct LPP_GNSS_SSR_CodeBiasReq_r15 {
	LPP_GNSS_SignalIDs_t	 signal_and_tracking_mode_ID_Map_r15;
	struct LPP_GNSS_NavListInfo_r15	*storedNavList_r15;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_GNSS_SSR_CodeBiasReq_r15__ext1 {
		long	*ssr_IntegrityCodeBiasBoundsReq_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_SSR_CodeBiasReq_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_ssr_IntegrityCodeBiasBoundsReq_r17_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_SSR_CodeBiasReq_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_SSR_CodeBiasReq_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_SSR_CodeBiasReq_r15_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_SSR_CodeBiasReq_r15_H_ */
#include <asn_internal.h>
