/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_TDOA_RequestAssistanceData_r16_H_
#define	_LPP_NR_DL_TDOA_RequestAssistanceData_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NR-PhysCellID-r16.h"
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_TDOA_RequestAssistanceData_r16__nr_AdType_r16 {
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__nr_AdType_r16_dl_prs	= 0,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__nr_AdType_r16_posCalc	= 1
} e_LPP_NR_DL_TDOA_RequestAssistanceData_r16__nr_AdType_r16;
typedef enum LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17 {
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_trpLoc	= 0,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_beamInfo	= 1,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_rtdInfo	= 2,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_losNlosInfo	= 3,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_trpTEG_Info	= 4,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_nr_IntegrityBounds_r18	= 5,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17_pruInfo_r18	= 6
} e_LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_PosCalcAssistanceRequest_r17;
typedef enum LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17 {
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17_eAoD	= 0,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17_eAoA	= 1
} e_LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17;
typedef enum LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__pre_configured_AssistanceDataRequest_r17 {
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__pre_configured_AssistanceDataRequest_r17_true	= 0
} e_LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1__pre_configured_AssistanceDataRequest_r17;
typedef enum LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18 {
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_serviceParameters	= 0,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_serviceAlert	= 1,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_riskParameters	= 2,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_integrityParaTRP_Loc	= 3,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_integrityParaBeamInfo	= 4,
	LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18_integrityParaRTD_Info	= 5
} e_LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2__nr_IntegrityAssistanceRequest_r18;

/* Forward declarations */
struct LPP_NR_On_Demand_DL_PRS_Request_r17;
struct LPP_NR_PeriodicAssistDataReq_r18;

/* LPP_NR-DL-TDOA-RequestAssistanceData-r16 */
typedef struct LPP_NR_DL_TDOA_RequestAssistanceData_r16 {
	LPP_NR_PhysCellID_r16_t	*nr_PhysCellID_r16;	/* OPTIONAL */
	BIT_STRING_t	 nr_AdType_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext1 {
		BIT_STRING_t	*nr_PosCalcAssistanceRequest_r17;	/* OPTIONAL */
		struct LPP_NR_On_Demand_DL_PRS_Request_r17	*nr_on_demand_DL_PRS_Request_r17;	/* OPTIONAL */
		long	*nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17;	/* OPTIONAL */
		long	*pre_configured_AssistanceDataRequest_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_DL_TDOA_RequestAssistanceData_r16__ext2 {
		struct LPP_NR_PeriodicAssistDataReq_r18	*nr_PeriodicAssistDataReq_r18;	/* OPTIONAL */
		BIT_STRING_t	*nr_IntegrityAssistanceRequest_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_TDOA_RequestAssistanceData_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_DL_PRS_ExpectedAoD_or_AoA_Request_r17_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_pre_configured_AssistanceDataRequest_r17_20;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_TDOA_RequestAssistanceData_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_TDOA_RequestAssistanceData_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_TDOA_RequestAssistanceData_r16_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_TDOA_RequestAssistanceData_r16_H_ */
#include <asn_internal.h>
