/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_SSR_OrbitCorrectionSatelliteElement_r15_H_
#define	_LPP_SSR_OrbitCorrectionSatelliteElement_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_SV-ID.h"
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_SSR_IntegrityOrbitBounds_r17;

/* LPP_SSR-OrbitCorrectionSatelliteElement-r15 */
typedef struct LPP_SSR_OrbitCorrectionSatelliteElement_r15 {
	LPP_SV_ID_t	 svID_r15;
	BIT_STRING_t	 iod_r15;
	long	 delta_radial_r15;
	long	 delta_AlongTrack_r15;
	long	 delta_CrossTrack_r15;
	long	*dot_delta_radial_r15;	/* OPTIONAL */
	long	*dot_delta_AlongTrack_r15;	/* OPTIONAL */
	long	*dot_delta_CrossTrack_r15;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_SSR_OrbitCorrectionSatelliteElement_r15__ext1 {
		struct LPP_SSR_IntegrityOrbitBounds_r17	*ssr_IntegrityOrbitBounds_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_SSR_OrbitCorrectionSatelliteElement_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_SSR_OrbitCorrectionSatelliteElement_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_SSR_OrbitCorrectionSatelliteElement_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_SSR_OrbitCorrectionSatelliteElement_r15_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_SSR_OrbitCorrectionSatelliteElement_r15_H_ */
#include <asn_internal.h>
