/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_CommonIEsProvideCapabilities_H_
#define	_LPP_CommonIEsProvideCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_SegmentationInfo-r14.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include <BOOLEAN.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_CommonIEsProvideCapabilities__ext1__lpp_message_segmentation_r14 {
	LPP_CommonIEsProvideCapabilities__ext1__lpp_message_segmentation_r14_serverToTarget	= 0,
	LPP_CommonIEsProvideCapabilities__ext1__lpp_message_segmentation_r14_targetToServer	= 1
} e_LPP_CommonIEsProvideCapabilities__ext1__lpp_message_segmentation_r14;
typedef enum LPP_CommonIEsProvideCapabilities__ext2__locationEstimateAndMeasurementReporting_r18 {
	LPP_CommonIEsProvideCapabilities__ext2__locationEstimateAndMeasurementReporting_r18_supported	= 0
} e_LPP_CommonIEsProvideCapabilities__ext2__locationEstimateAndMeasurementReporting_r18;

/* LPP_CommonIEsProvideCapabilities */
typedef struct LPP_CommonIEsProvideCapabilities {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_CommonIEsProvideCapabilities__ext1 {
		LPP_SegmentationInfo_r14_t	*segmentationInfo_r14;	/* OPTIONAL */
		BIT_STRING_t	*lpp_message_segmentation_r14;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_CommonIEsProvideCapabilities__ext2 {
		BOOLEAN_t	*remoteUE_Indication_r18;	/* OPTIONAL */
		long	*locationEstimateAndMeasurementReporting_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_CommonIEsProvideCapabilities_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_locationEstimateAndMeasurementReporting_r18_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_CommonIEsProvideCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_CommonIEsProvideCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_CommonIEsProvideCapabilities_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_CommonIEsProvideCapabilities_H_ */
#include <asn_internal.h>
