/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_TargetIntegrityRisk_r17_H_
#define	_LPP_TargetIntegrityRisk_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_TargetIntegrityRisk-r17 */
typedef long	 LPP_TargetIntegrityRisk_r17_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LPP_TargetIntegrityRisk_r17_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LPP_TargetIntegrityRisk_r17;
asn_struct_free_f LPP_TargetIntegrityRisk_r17_free;
asn_struct_print_f LPP_TargetIntegrityRisk_r17_print;
asn_constr_check_f LPP_TargetIntegrityRisk_r17_constraint;
ber_type_decoder_f LPP_TargetIntegrityRisk_r17_decode_ber;
der_type_encoder_f LPP_TargetIntegrityRisk_r17_encode_der;
xer_type_decoder_f LPP_TargetIntegrityRisk_r17_decode_xer;
xer_type_encoder_f LPP_TargetIntegrityRisk_r17_encode_xer;
jer_type_encoder_f LPP_TargetIntegrityRisk_r17_encode_jer;
per_type_decoder_f LPP_TargetIntegrityRisk_r17_decode_uper;
per_type_encoder_f LPP_TargetIntegrityRisk_r17_encode_uper;
per_type_decoder_f LPP_TargetIntegrityRisk_r17_decode_aper;
per_type_encoder_f LPP_TargetIntegrityRisk_r17_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_TargetIntegrityRisk_r17_H_ */
#include <asn_internal.h>
