/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_H_
#define	_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18_mhz40	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18_mhz50	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18_mhz80	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18_mhz100	= 3
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR1_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR2_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR2_r18_mhz100	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR2_r18_mhz200	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR2_r18_mhz400	= 2
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_BandwidthAcrossAllHopsFR2_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18_n2	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18_n3	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18_n4	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18_n5	= 3,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18_n6	= 4
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumTxFH_Hops_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR1_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR1_r18_n70	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR1_r18_n140	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR1_r18_n210	= 2
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR1_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR2_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR2_r18_n35	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR2_r18_n70	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR2_r18_n140	= 2
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__rf_TxRetuneTimeFR2_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18_n100	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18_n140	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18_n200	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18_n300	= 3,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18_n500	= 4
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__switchTimeBetweenActiveBWP_FrequencyHop_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18_n0	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18_n1	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18_n2	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18_n4	= 3
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__numOfOverlappingPRB_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n1	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n2	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n4	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n8	= 3,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n16	= 4,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n32	= 5,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18_n64	= 6
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourcePeriodic_r18;
typedef enum LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18 {
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n0	= 0,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n1	= 1,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n2	= 2,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n4	= 3,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n8	= 4,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n16	= 5,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n32	= 6,
	LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18_n64	= 7
} e_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18__maximumSRS_ResourceSemipersistent_r18;

/* LPP_PosSRS-TxFrequencyHoppingRRC-Inactive-r18 */
typedef struct LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18 {
	long	*maximumSRS_BandwidthAcrossAllHopsFR1_r18;	/* OPTIONAL */
	long	*maximumSRS_BandwidthAcrossAllHopsFR2_r18;	/* OPTIONAL */
	long	*maximumTxFH_Hops_r18;	/* OPTIONAL */
	long	*rf_TxRetuneTimeFR1_r18;	/* OPTIONAL */
	long	*rf_TxRetuneTimeFR2_r18;	/* OPTIONAL */
	long	*switchTimeBetweenActiveBWP_FrequencyHop_r18;	/* OPTIONAL */
	long	*numOfOverlappingPRB_r18;	/* OPTIONAL */
	long	*maximumSRS_ResourcePeriodic_r18;	/* OPTIONAL */
	long	*maximumSRS_ResourceSemipersistent_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maximumSRS_BandwidthAcrossAllHopsFR1_r18_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maximumSRS_BandwidthAcrossAllHopsFR2_r18_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maximumTxFH_Hops_r18_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_rf_TxRetuneTimeFR1_r18_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_rf_TxRetuneTimeFR2_r18_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_switchTimeBetweenActiveBWP_FrequencyHop_r18_25;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_numOfOverlappingPRB_r18_31;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maximumSRS_ResourcePeriodic_r18_36;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_maximumSRS_ResourceSemipersistent_r18_44;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_PosSRS_TxFrequencyHoppingRRC_Inactive_r18_H_ */
#include <asn_internal.h>
