/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_ScheduledLocationTimeSupportPerMode_r17_H_
#define	_LPP_ScheduledLocationTimeSupportPerMode_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_PositioningModes.h"
#include "LPP_GNSS-ID-Bitmap.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_PositioningModes;

/* LPP_ScheduledLocationTimeSupportPerMode-r17 */
typedef struct LPP_ScheduledLocationTimeSupportPerMode_r17 {
	struct LPP_PositioningModes	*utcTime_r17;	/* OPTIONAL */
	struct LPP_ScheduledLocationTimeSupportPerMode_r17__gnssTime_r17 {
		LPP_PositioningModes_t	 posModes_r17;
		LPP_GNSS_ID_Bitmap_t	 gnss_TimeIDs_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *gnssTime_r17;
	struct LPP_PositioningModes	*e_utraTime_r17;	/* OPTIONAL */
	struct LPP_PositioningModes	*nrTime_r17;	/* OPTIONAL */
	struct LPP_PositioningModes	*relativeTime_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_ScheduledLocationTimeSupportPerMode_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_ScheduledLocationTimeSupportPerMode_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_ScheduledLocationTimeSupportPerMode_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_ScheduledLocationTimeSupportPerMode_r17_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ScheduledLocationTimeSupportPerMode_r17_H_ */
#include <asn_internal.h>
