/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_H_
#define	_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NR-DL-PRS-ResourceID-r16.h"
#include "LPP_NR-DL-PRS-ResourceSetID-r16.h"
#include "LPP_NR-TimeStamp-r16.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_AoD_AdditionalMeasurementElement_r17__ext1__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18 {
	LPP_NR_DL_AoD_AdditionalMeasurementElement_r17__ext1__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_singleHop	= 0,
	LPP_NR_DL_AoD_AdditionalMeasurementElement_r17__ext1__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_multipleHop	= 1
} e_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17__ext1__nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18;

/* Forward declarations */
struct LPP_LOS_NLOS_Indicator_r17;

/* LPP_NR-DL-AoD-AdditionalMeasurementElement-r17 */
typedef struct LPP_NR_DL_AoD_AdditionalMeasurementElement_r17 {
	LPP_NR_DL_PRS_ResourceID_r16_t	*nr_DL_PRS_ResourceID_r17;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceSetID_r16_t	*nr_DL_PRS_ResourceSetID_r17;	/* OPTIONAL */
	LPP_NR_TimeStamp_r16_t	 nr_TimeStamp_r17;
	long	*nr_DL_PRS_RSRP_ResultDiff_r17;	/* OPTIONAL */
	long	*nr_DL_PRS_RxBeamIndex_r17;	/* OPTIONAL */
	long	*nr_DL_PRS_FirstPathRSRP_ResultDiff_r17;	/* OPTIONAL */
	struct LPP_LOS_NLOS_Indicator_r17	*nr_los_nlos_IndicatorPerResource_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_AoD_AdditionalMeasurementElement_r17__ext1 {
		long	*nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_ReportDL_PRS_MeasBasedOnSingleOrMultiHopRx_r18_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_AoD_AdditionalMeasurementElement_r17_H_ */
#include <asn_internal.h>
