/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_LocalOrigin_r18_H_
#define	_LPP_LocalOrigin_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_HighAccuracyEllipsoidPointWithAltitudeAndUncertaintyEllipsoid_r15;

/* LPP_LocalOrigin-r18 */
typedef struct LPP_LocalOrigin_r18 {
	VisibleString_t	 coordinateID_r18;
	struct LPP_HighAccuracyEllipsoidPointWithAltitudeAndUncertaintyEllipsoid_r15	*point_r18;	/* OPTIONAL */
	long	*horizAxesOrientation_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_LocalOrigin_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_LocalOrigin_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_LocalOrigin_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_LocalOrigin_r18_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_LocalOrigin_r18_H_ */
#include <asn_internal.h>
