/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_SSR_PhaseBiasSupport_r16_H_
#define	_LPP_GNSS_SSR_PhaseBiasSupport_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_GNSS-SignalIDs.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_GNSS_SSR_PhaseBiasSupport_r16__ext1__ssr_IntegrityPhaseBiasBoundsSup_r17 {
	LPP_GNSS_SSR_PhaseBiasSupport_r16__ext1__ssr_IntegrityPhaseBiasBoundsSup_r17_supported	= 0
} e_LPP_GNSS_SSR_PhaseBiasSupport_r16__ext1__ssr_IntegrityPhaseBiasBoundsSup_r17;

/* LPP_GNSS-SSR-PhaseBiasSupport-r16 */
typedef struct LPP_GNSS_SSR_PhaseBiasSupport_r16 {
	LPP_GNSS_SignalIDs_t	 signal_and_tracking_mode_ID_Sup_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_GNSS_SSR_PhaseBiasSupport_r16__ext1 {
		long	*ssr_IntegrityPhaseBiasBoundsSup_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_SSR_PhaseBiasSupport_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_ssr_IntegrityPhaseBiasBoundsSup_r17_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_SSR_PhaseBiasSupport_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_SSR_PhaseBiasSupport_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_SSR_PhaseBiasSupport_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_SSR_PhaseBiasSupport_r16_H_ */
#include <asn_internal.h>
