/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_ECID_ProvideCapabilities_r16_H_
#define	_LPP_NR_ECID_ProvideCapabilities_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16 {
	LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_ssrsrpSup	= 0,
	LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_ssrsrqSup	= 1,
	LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_csirsrpSup	= 2,
	LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16_csirsrqSup	= 3
} e_LPP_NR_ECID_ProvideCapabilities_r16__nr_ECID_MeasSupported_r16;
typedef enum LPP_NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16 {
	LPP_NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16_supported	= 0
} e_LPP_NR_ECID_ProvideCapabilities_r16__periodicalReporting_r16;
typedef enum LPP_NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16 {
	LPP_NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16_supported	= 0
} e_LPP_NR_ECID_ProvideCapabilities_r16__triggeredReporting_r16;
typedef enum LPP_NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17 {
	LPP_NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17_supported	= 0
} e_LPP_NR_ECID_ProvideCapabilities_r16__ext1__ten_ms_unit_ResponseTime_r17;

/* Forward declarations */
struct LPP_ScheduledLocationTimeSupport_r17;
struct LPP_PeriodicReportingIntervalMsSupport_r18;

/* LPP_NR-ECID-ProvideCapabilities-r16 */
typedef struct LPP_NR_ECID_ProvideCapabilities_r16 {
	BIT_STRING_t	 nr_ECID_MeasSupported_r16;
	long	*periodicalReporting_r16;	/* OPTIONAL */
	long	*triggeredReporting_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_ECID_ProvideCapabilities_r16__ext1 {
		long	*ten_ms_unit_ResponseTime_r17;	/* OPTIONAL */
		struct LPP_ScheduledLocationTimeSupport_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_ECID_ProvideCapabilities_r16__ext2 {
		struct LPP_PeriodicReportingIntervalMsSupport_r18	*periodicReportingIntervalMsSupport_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_ECID_ProvideCapabilities_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_periodicalReporting_r16_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_triggeredReporting_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_ten_ms_unit_ResponseTime_r17_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_ECID_ProvideCapabilities_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_ECID_ProvideCapabilities_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_ECID_ProvideCapabilities_r16_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_ECID_ProvideCapabilities_r16_H_ */
#include <asn_internal.h>
