/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_BT_BeaconInfoElement_r18_H_
#define	_LPP_BT_BeaconInfoElement_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_RelativeLocation_r16;
struct LPP_LCS_GCS_TranslationParameter_r16;
struct LPP_BT_AntArrayConfig_r18;
struct LPP_BT_AoD_TransmConfig_r18;
struct LPP_BT_AntElement_r18;
struct LPP_BT_AntSwitchElement_r18;

/* LPP_BT-BeaconInfoElement-r18 */
typedef struct LPP_BT_BeaconInfoElement_r18 {
	BIT_STRING_t	 bt_Addr_r18;
	struct LPP_RelativeLocation_r16	*bt_BeaconLocation_r18;	/* OPTIONAL */
	struct LPP_LCS_GCS_TranslationParameter_r16	*bt_LCS_GCS_TranslationParameter_r18;	/* OPTIONAL */
	struct LPP_BT_AntArrayConfig_r18	*bt_antArrayConfig_r18;	/* OPTIONAL */
	struct LPP_BT_BeaconInfoElement_r18__bt_antElementList_r18 {
		A_SEQUENCE_OF(struct LPP_BT_AntElement_r18) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *bt_antElementList_r18;
	struct LPP_BT_BeaconInfoElement_r18__bt_antSwitchingPattern_r18 {
		A_SEQUENCE_OF(struct LPP_BT_AntSwitchElement_r18) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *bt_antSwitchingPattern_r18;
	struct LPP_BT_AoD_TransmConfig_r18	*bt_AoD_TransmConfig_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_BT_BeaconInfoElement_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_BT_BeaconInfoElement_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_BT_BeaconInfoElement_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_BT_BeaconInfoElement_r18_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_BT_BeaconInfoElement_r18_H_ */
#include <asn_internal.h>
