/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_DL_PRS_QCL_InfoReq_r17_H_
#define	_LPP_DL_PRS_QCL_InfoReq_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_NR-DL-PRS-ResourceSetID-r16.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR {
	LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR_NOTHING,	/* No components present */
	LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR_dl_prs_QCL_InfoRecPerResourceSet_r17,
	LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR_dl_prs_QCL_Info_requested_r17
} LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR;

/* Forward declarations */
struct LPP_DL_PRS_QCL_Info_r16;

/* LPP_DL-PRS-QCL-InfoReq-r17 */
typedef struct LPP_DL_PRS_QCL_InfoReq_r17 {
	LPP_NR_DL_PRS_ResourceSetID_r16_t	 nr_DL_PRS_ResourceSetID_r17;
	struct LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17 {
		LPP_DL_PRS_QCL_InfoReq_r17__dl_prs_QCL_InformationReq_r17_PR present;
		union LPP_DL_PRS_QCL_InfoReq_r17__LPP_dl_prs_QCL_InformationReq_r17_u {
			struct LPP_DL_PRS_QCL_Info_r16	*dl_prs_QCL_InfoRecPerResourceSet_r17;
			NULL_t	 dl_prs_QCL_Info_requested_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dl_prs_QCL_InformationReq_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_DL_PRS_QCL_InfoReq_r17__ext1 {
		struct LPP_DL_PRS_QCL_InfoReq_r17__ext1__dl_prs_QCL_InfoRecPerResource_r17 {
			A_SEQUENCE_OF(struct LPP_DL_PRS_QCL_Info_r16) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *dl_prs_QCL_InfoRecPerResource_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_DL_PRS_QCL_InfoReq_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_DL_PRS_QCL_InfoReq_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_DL_PRS_QCL_InfoReq_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_DL_PRS_QCL_InfoReq_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_DL_PRS_QCL_InfoReq_r17_H_ */
#include <asn_internal.h>
