/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_ElevationElement_R17_H_
#define	_LPP_ElevationElement_R17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_BeamPowerElement_r17;

/* LPP_ElevationElement-R17 */
typedef struct LPP_ElevationElement_R17 {
	long	*elevation_r17;	/* OPTIONAL */
	long	*elevation_fine_r17;	/* OPTIONAL */
	struct LPP_ElevationElement_R17__beamPowerList_r17 {
		A_SEQUENCE_OF(struct LPP_BeamPowerElement_r17) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} beamPowerList_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_ElevationElement_R17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_ElevationElement_R17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_ElevationElement_R17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_ElevationElement_R17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_ElevationElement_R17_H_ */
#include <asn_internal.h>
