/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_H_
#define	_LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_NR-DL-PRS-ResourceSetID-r16.h"
#include "LPP_NR-DL-PRS-ResourceID-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LPP_NR-AggregatedDL-PRS-ResourceInfo-Element-r18 */
typedef struct LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18 {
	long	*aggregatedDL_PRS_ID_r18;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceSetID_r16_t	*nr_DL_PRS_ResourceSetID_r18;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceID_r16_t	*nr_DL_PRS_ResourceID_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_AggregatedDL_PRS_ResourceInfo_Element_r18_H_ */
#include <asn_internal.h>
