/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_SRS_TxTEG_Element_r17_H_
#define	_LPP_NR_SRS_TxTEG_Element_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_ARFCN-ValueNR-r15.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_NR_TimeStamp_r16;

/* LPP_NR-SRS-TxTEG-Element-r17 */
typedef struct LPP_NR_SRS_TxTEG_Element_r17 {
	struct LPP_NR_TimeStamp_r16	*nr_TimeStamp_r17;	/* OPTIONAL */
	long	 nr_UE_Tx_TEG_ID_r17;
	struct LPP_NR_SRS_TxTEG_Element_r17__carrierFreq_r17 {
		LPP_ARFCN_ValueNR_r15_t	 absoluteFrequencyPointA_r17;
		long	 offsetToPointA_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierFreq_r17;
	struct LPP_NR_SRS_TxTEG_Element_r17__srs_PosResourceList_r17 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} srs_PosResourceList_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_SRS_TxTEG_Element_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_SRS_TxTEG_Element_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_SRS_TxTEG_Element_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_SRS_TxTEG_Element_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_SRS_TxTEG_Element_r17_H_ */
#include <asn_internal.h>
