/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_PRU_RSCP_MeasElement_r18_H_
#define	_LPP_NR_PRU_RSCP_MeasElement_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "LPP_NR-PhysCellID-r16.h"
#include "LPP_ARFCN-ValueNR-r15.h"
#include "LPP_NR-DL-PRS-ResourceID-r16.h"
#include "LPP_NR-DL-PRS-ResourceSetID-r16.h"
#include "LPP_NR-TimeStamp-r16.h"
#include <constr_CHOICE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR {
	LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR_NOTHING,	/* No components present */
	LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR_perTRP,
	LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR_perResource
} LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR;

/* Forward declarations */
struct LPP_NCGI_r15;
struct LPP_NR_PhaseQuality_r18;
struct LPP_NR_PRU_RSCP_AdditionalMeasurements_r18;
struct LPP_LOS_NLOS_Indicator_r17;
struct LPP_NR_RSCP_AdditionalMeasurements_r18;

/* LPP_NR-PRU-RSCP-MeasElement-r18 */
typedef struct LPP_NR_PRU_RSCP_MeasElement_r18 {
	long	 dl_PRS_ID_r18;
	LPP_NR_PhysCellID_r16_t	*nr_PhysCellID_r18;	/* OPTIONAL */
	struct LPP_NCGI_r15	*nr_CellGlobalID_r18;	/* OPTIONAL */
	LPP_ARFCN_ValueNR_r15_t	*nr_ARFCN_r18;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceID_r16_t	*nr_DL_PRS_ResourceID_r18;	/* OPTIONAL */
	LPP_NR_DL_PRS_ResourceSetID_r16_t	*nr_DL_PRS_ResourceSetID_r18;	/* OPTIONAL */
	LPP_NR_TimeStamp_r16_t	 nr_TimeStamp_r18;
	struct LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18 {
		LPP_NR_PRU_RSCP_MeasElement_r18__nr_los_nlos_Indicator_r18_PR present;
		union LPP_NR_PRU_RSCP_MeasElement_r18__LPP_nr_los_nlos_Indicator_r18_u {
			struct LPP_LOS_NLOS_Indicator_r17	*perTRP;
			struct LPP_LOS_NLOS_Indicator_r17	*perResource;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nr_los_nlos_Indicator_r18;
	long	*nr_RSCP_r18;	/* OPTIONAL */
	long	*nr_DL_PRS_RSRP_Result_r18;	/* OPTIONAL */
	long	*nr_DL_PRS_FirstPathRSRP_Result_r18;	/* OPTIONAL */
	struct LPP_NR_PhaseQuality_r18	*nr_PhaseQuality_r18;	/* OPTIONAL */
	struct LPP_NR_PRU_RSCP_MeasElement_r18__nr_PRU_RSCP_AddSampleMeasurements_r18 {
		A_SEQUENCE_OF(struct LPP_NR_RSCP_AdditionalMeasurements_r18) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nr_PRU_RSCP_AddSampleMeasurements_r18;
	struct LPP_NR_PRU_RSCP_MeasElement_r18__nr_PRU_RSRP_AddSampleMeasurements_r18 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nr_PRU_RSRP_AddSampleMeasurements_r18;
	struct LPP_NR_PRU_RSCP_MeasElement_r18__nr_PRU_FirstPathRSRP_ResultDiff_AddSampleMeasurements_r18 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nr_PRU_FirstPathRSRP_ResultDiff_AddSampleMeasurements_r18;
	struct LPP_NR_PRU_RSCP_AdditionalMeasurements_r18	*nr_PRU_RSCP_AdditionalMeasurements_r18;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_PRU_RSCP_MeasElement_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_PRU_RSCP_MeasElement_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_PRU_RSCP_MeasElement_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_PRU_RSCP_MeasElement_r18_1[16];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_PRU_RSCP_MeasElement_r18_H_ */
#include <asn_internal.h>
