/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_BT_BeaconInfo_r18_H_
#define	_LPP_BT_BeaconInfo_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_ReferencePoint-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_BT_BeaconInfoElement_r18;

/* LPP_BT-BeaconInfo-r18 */
typedef struct LPP_BT_BeaconInfo_r18 {
	LPP_ReferencePoint_r16_t	 referencePoint_r18;
	struct LPP_BT_BeaconInfo_r18__bt_BeaconInfoList_r18 {
		A_SEQUENCE_OF(struct LPP_BT_BeaconInfoElement_r18) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} bt_BeaconInfoList_r18;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_BT_BeaconInfo_r18_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_BT_BeaconInfo_r18;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_BT_BeaconInfo_r18_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_BT_BeaconInfo_r18_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_BT_BeaconInfo_r18_H_ */
#include <asn_internal.h>
