/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "LPP_NR-PRU-DL-Info-r18.h"

#include "LPP_LocationCoordinates.h"
#include "LPP_NR-DL-TDOA-SignalMeasurementInformation-r16.h"
#include "LPP_NR-DL-AoD-SignalMeasurementInformation-r16.h"
#include "LPP_NR-PRU-RSCP-MeasurementInformation-r18.h"
asn_TYPE_member_t asn_MBR_LPP_NR_PRU_DL_Info_r18_1[] = {
	{ ATF_POINTER, 4, offsetof(struct LPP_NR_PRU_DL_Info_r18, nr_PRU_LocationInfo_r18),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LPP_LocationCoordinates,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-PRU-LocationInfo-r18"
		},
	{ ATF_POINTER, 3, offsetof(struct LPP_NR_PRU_DL_Info_r18, nr_PRU_DL_TDOA_MeasInfo_r18),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NR_DL_TDOA_SignalMeasurementInformation_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-PRU-DL-TDOA-MeasInfo-r18"
		},
	{ ATF_POINTER, 2, offsetof(struct LPP_NR_PRU_DL_Info_r18, nr_PRU_DL_AoD_MeasInfo_r18),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NR_DL_AoD_SignalMeasurementInformation_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-PRU-DL-AoD-MeasInfo-r18"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_NR_PRU_DL_Info_r18, nr_PRU_RSCP_MeasInfo_r18),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_NR_PRU_RSCP_MeasurementInformation_r18,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nr-PRU-RSCP-MeasInfo-r18"
		},
};
static const int asn_MAP_LPP_NR_PRU_DL_Info_r18_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_NR_PRU_DL_Info_r18_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nr-PRU-LocationInfo-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nr-PRU-DL-TDOA-MeasInfo-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nr-PRU-DL-AoD-MeasInfo-r18 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* nr-PRU-RSCP-MeasInfo-r18 */
};
asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_PRU_DL_Info_r18_specs_1 = {
	sizeof(struct LPP_NR_PRU_DL_Info_r18),
	offsetof(struct LPP_NR_PRU_DL_Info_r18, _asn_ctx),
	asn_MAP_LPP_NR_PRU_DL_Info_r18_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_LPP_NR_PRU_DL_Info_r18_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LPP_NR_PRU_DL_Info_r18 = {
	"NR-PRU-DL-Info-r18",
	"NR-PRU-DL-Info-r18",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1,
	sizeof(asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1)
		/sizeof(asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1[0]), /* 1 */
	asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1)
		/sizeof(asn_DEF_LPP_NR_PRU_DL_Info_r18_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_NR_PRU_DL_Info_r18_1,
	4,	/* Elements count */
	&asn_SPC_LPP_NR_PRU_DL_Info_r18_specs_1	/* Additional specs */
};

