/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#include "LPP_GNSS-LocationInformation.h"

#include "LPP_HA-GNSS-Metrics-r17.h"
static asn_TYPE_member_t asn_MBR_LPP_ext1_5[] = {
	{ ATF_POINTER, 1, offsetof(struct LPP_GNSS_LocationInformation__ext1, ha_GNSS_Metrics_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_HA_GNSS_Metrics_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ha-GNSS-Metrics-r17"
		},
};
static const int asn_MAP_LPP_ext1_oms_5[] = { 0 };
static const ber_tlv_tag_t asn_DEF_LPP_ext1_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_ext1_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ha-GNSS-Metrics-r17 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LPP_ext1_specs_5 = {
	sizeof(struct LPP_GNSS_LocationInformation__ext1),
	offsetof(struct LPP_GNSS_LocationInformation__ext1, _asn_ctx),
	asn_MAP_LPP_ext1_tag2el_5,
	1,	/* Count of tags in the map */
	asn_MAP_LPP_ext1_oms_5,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_LPP_ext1_5 = {
	"ext1",
	"ext1",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_ext1_tags_5,
	sizeof(asn_DEF_LPP_ext1_tags_5)
		/sizeof(asn_DEF_LPP_ext1_tags_5[0]) - 1, /* 1 */
	asn_DEF_LPP_ext1_tags_5,	/* Same as above */
	sizeof(asn_DEF_LPP_ext1_tags_5)
		/sizeof(asn_DEF_LPP_ext1_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_ext1_5,
	1,	/* Elements count */
	&asn_SPC_LPP_ext1_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LPP_GNSS_LocationInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_GNSS_LocationInformation, measurementReferenceTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_MeasurementReferenceTime,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"measurementReferenceTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LPP_GNSS_LocationInformation, agnss_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LPP_GNSS_ID_Bitmap,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"agnss-List"
		},
	{ ATF_POINTER, 1, offsetof(struct LPP_GNSS_LocationInformation, ext1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_LPP_ext1_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ext1"
		},
};
static const int asn_MAP_LPP_GNSS_LocationInformation_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_LPP_GNSS_LocationInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LPP_GNSS_LocationInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measurementReferenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* agnss-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ext1 */
};
asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_LocationInformation_specs_1 = {
	sizeof(struct LPP_GNSS_LocationInformation),
	offsetof(struct LPP_GNSS_LocationInformation, _asn_ctx),
	asn_MAP_LPP_GNSS_LocationInformation_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LPP_GNSS_LocationInformation_oms_1,	/* Optional members */
	0, 1,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_LocationInformation = {
	"GNSS-LocationInformation",
	"GNSS-LocationInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_LPP_GNSS_LocationInformation_tags_1,
	sizeof(asn_DEF_LPP_GNSS_LocationInformation_tags_1)
		/sizeof(asn_DEF_LPP_GNSS_LocationInformation_tags_1[0]), /* 1 */
	asn_DEF_LPP_GNSS_LocationInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_LPP_GNSS_LocationInformation_tags_1)
		/sizeof(asn_DEF_LPP_GNSS_LocationInformation_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_LPP_GNSS_LocationInformation_1,
	3,	/* Elements count */
	&asn_SPC_LPP_GNSS_LocationInformation_specs_1	/* Additional specs */
};

