/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_SpatialDelta_r18_H_
#define	_LPP_SpatialDelta_r18_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_SpatialDelta_r18 {
	LPP_SpatialDelta_r18_n1	= 0,
	LPP_SpatialDelta_r18_n2	= 1,
	LPP_SpatialDelta_r18_n3	= 2,
	LPP_SpatialDelta_r18_n4	= 3,
	LPP_SpatialDelta_r18_n5	= 4,
	LPP_SpatialDelta_r18_n10	= 5,
	LPP_SpatialDelta_r18_n20	= 6,
	LPP_SpatialDelta_r18_n50	= 7,
	LPP_SpatialDelta_r18_n100	= 8
} e_LPP_SpatialDelta_r18;

/* LPP_SpatialDelta-r18 */
typedef long	 LPP_SpatialDelta_r18_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LPP_SpatialDelta_r18_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LPP_SpatialDelta_r18;
extern const asn_INTEGER_specifics_t asn_SPC_LPP_SpatialDelta_r18_specs_1;
asn_struct_free_f LPP_SpatialDelta_r18_free;
asn_struct_print_f LPP_SpatialDelta_r18_print;
asn_constr_check_f LPP_SpatialDelta_r18_constraint;
ber_type_decoder_f LPP_SpatialDelta_r18_decode_ber;
der_type_encoder_f LPP_SpatialDelta_r18_encode_der;
xer_type_decoder_f LPP_SpatialDelta_r18_decode_xer;
xer_type_encoder_f LPP_SpatialDelta_r18_encode_xer;
jer_type_encoder_f LPP_SpatialDelta_r18_encode_jer;
per_type_decoder_f LPP_SpatialDelta_r18_decode_uper;
per_type_encoder_f LPP_SpatialDelta_r18_encode_uper;
per_type_decoder_f LPP_SpatialDelta_r18_decode_aper;
per_type_encoder_f LPP_SpatialDelta_r18_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_SpatialDelta_r18_H_ */
#include <asn_internal.h>
