/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_DL_TDOA_ProvideCapabilities_r16_H_
#define	_LPP_NR_DL_TDOA_ProvideCapabilities_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_PositioningModes.h"
#include "LPP_NR-DL-PRS-ResourcesCapability-r16.h"
#include "LPP_NR-DL-TDOA-MeasurementCapability-r16.h"
#include "LPP_NR-DL-PRS-QCL-ProcessingCapability-r16.h"
#include "LPP_NR-DL-PRS-ProcessingCapability-r16.h"
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include "LPP_LOS-NLOS-IndicatorType2-r17.h"
#include "LPP_LOS-NLOS-IndicatorGranularity2-r17.h"
#include <constr_SEQUENCE.h>
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__additionalPathsReport_r16 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__additionalPathsReport_r16_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__additionalPathsReport_r16;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_trpLocSup	= 0,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_beamInfoSup	= 1,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_rtdInfoSup	= 2,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_trpTEG_InfoSup	= 3,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_nr_IntegritySup_r18	= 4,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17_pruInfoSup_r18	= 5
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_PosCalcAssistanceSupport_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17_eAoD	= 0,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17_eAoA	= 1
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n4	= 0,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n6	= 1,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17_n8	= 2
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__additionalPathsExtSupport_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__multiMeasInSameMeasReport_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__mg_ActivationRequest_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext2__posMeasGapSupport_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext3__multiLocationEstimateInSameMeasReport_r17 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext3__multiLocationEstimateInSameMeasReport_r17_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext3__multiLocationEstimateInSameMeasReport_r17;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__periodicAssistanceData_r18 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__periodicAssistanceData_r18_solicited	= 0,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__periodicAssistanceData_r18_unsolicited	= 1
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__periodicAssistanceData_r18;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_serviceParametersSup	= 0,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_serviceAlertSup	= 1,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_riskParametersSup	= 2,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_integrityParaTRP_LocSup	= 3,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_integrityParaBeamInfoSup	= 4,
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18_integrityParaRTD_InfoSup	= 5
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_IntegrityAssistanceSupport_r18;
typedef enum LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_DL_TDOA_OnDemandPRS_ForBWA_Support_r18 {
	LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_DL_TDOA_OnDemandPRS_ForBWA_Support_r18_supported	= 0
} e_LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4__nr_DL_TDOA_OnDemandPRS_ForBWA_Support_r18;

/* Forward declarations */
struct LPP_PositioningModes;
struct LPP_NR_On_Demand_DL_PRS_Support_r17;
struct LPP_ScheduledLocationTimeSupportPerMode_r17;
struct LPP_LocationCoordinateTypes;
struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18;

/* LPP_NR-DL-TDOA-ProvideCapabilities-r16 */
typedef struct LPP_NR_DL_TDOA_ProvideCapabilities_r16 {
	LPP_PositioningModes_t	 nr_DL_TDOA_Mode_r16;
	LPP_NR_DL_PRS_ResourcesCapability_r16_t	 nr_DL_TDOA_PRS_Capability_r16;
	LPP_NR_DL_TDOA_MeasurementCapability_r16_t	 nr_DL_TDOA_MeasurementCapability_r16;
	LPP_NR_DL_PRS_QCL_ProcessingCapability_r16_t	 nr_DL_PRS_QCL_ProcessingCapability_r16;
	LPP_NR_DL_PRS_ProcessingCapability_r16_t	 nr_DL_PRS_ProcessingCapability_r16;
	long	*additionalPathsReport_r16;	/* OPTIONAL */
	struct LPP_PositioningModes	*periodicalReporting_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1 {
		struct LPP_PositioningModes	*ten_ms_unit_ResponseTime_r17;	/* OPTIONAL */
		BIT_STRING_t	*nr_PosCalcAssistanceSupport_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_los_nlos_AssistanceDataSupport_r17 {
			LPP_LOS_NLOS_IndicatorType2_r17_t	 type_r17;
			LPP_LOS_NLOS_IndicatorGranularity2_r17_t	 granularity_r17;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_los_nlos_AssistanceDataSupport_r17;
		BIT_STRING_t	*nr_DL_PRS_ExpectedAoD_or_AoA_Sup_r17;	/* OPTIONAL */
		struct LPP_NR_On_Demand_DL_PRS_Support_r17	*nr_DL_TDOA_On_Demand_DL_PRS_Support_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_los_nlos_IndicatorSupport_r17 {
			LPP_LOS_NLOS_IndicatorType2_r17_t	 type_r17;
			LPP_LOS_NLOS_IndicatorGranularity2_r17_t	 granularity_r17;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_los_nlos_IndicatorSupport_r17;
		long	*additionalPathsExtSupport_r17;	/* OPTIONAL */
		struct LPP_ScheduledLocationTimeSupportPerMode_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext1__nr_dl_prs_AssistanceDataValidity_r17 {
			long	*area_validity_r17;	/* OPTIONAL */
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_dl_prs_AssistanceDataValidity_r17;
		long	*multiMeasInSameMeasReport_r17;	/* OPTIONAL */
		long	*mg_ActivationRequest_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext2 {
		long	*posMeasGapSupport_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext3 {
		long	*multiLocationEstimateInSameMeasReport_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	struct LPP_NR_DL_TDOA_ProvideCapabilities_r16__ext4 {
		struct LPP_LocationCoordinateTypes	*locationCoordinateTypes_r18;	/* OPTIONAL */
		BIT_STRING_t	*periodicAssistanceData_r18;	/* OPTIONAL */
		BIT_STRING_t	*nr_IntegrityAssistanceSupport_r18;	/* OPTIONAL */
		long	*nr_DL_TDOA_OnDemandPRS_ForBWA_Support_r18;	/* OPTIONAL */
		struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18	*periodicReportingIntervalMsSupport_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_DL_TDOA_ProvideCapabilities_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_additionalPathsReport_r16_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_additionalPathsExtSupport_r17_32;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_multiMeasInSameMeasReport_r17_40;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_mg_ActivationRequest_r17_42;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_posMeasGapSupport_r17_45;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_multiLocationEstimateInSameMeasReport_r17_48;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_nr_DL_TDOA_OnDemandPRS_ForBWA_Support_r18_62;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_DL_TDOA_ProvideCapabilities_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_DL_TDOA_ProvideCapabilities_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_DL_TDOA_ProvideCapabilities_r16_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_DL_TDOA_ProvideCapabilities_r16_H_ */
#include <asn_internal.h>
