/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_NR_PositionCalculationAssistance_r16_H_
#define	_LPP_NR_PositionCalculationAssistance_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_NR_TRP_LocationInfo_r16;
struct LPP_NR_DL_PRS_BeamInfo_r16;
struct LPP_NR_RTD_Info_r16;
struct LPP_NR_TRP_BeamAntennaInfo_r17;
struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_Assistance_r17;
struct LPP_NR_DL_PRS_TRP_TEG_Info_r17;
struct LPP_NR_IntegrityServiceParameters_r18;
struct LPP_NR_IntegrityServiceAlert_r18;
struct LPP_NR_IntegrityRiskParameters_r18;
struct LPP_NR_IntegrityParametersTRP_LocationInfo_r18;
struct LPP_NR_IntegrityParametersDL_PRS_BeamInfo_r18;
struct LPP_NR_IntegrityParametersRTD_Info_r18;
struct LPP_NR_IntegrityParametersTRP_BeamAntennaInfo_r18;
struct LPP_NR_PRU_DL_Info_r18;

/* LPP_NR-PositionCalculationAssistance-r16 */
typedef struct LPP_NR_PositionCalculationAssistance_r16 {
	struct LPP_NR_TRP_LocationInfo_r16	*nr_TRP_LocationInfo_r16;	/* OPTIONAL */
	struct LPP_NR_DL_PRS_BeamInfo_r16	*nr_DL_PRS_BeamInfo_r16;	/* OPTIONAL */
	struct LPP_NR_RTD_Info_r16	*nr_RTD_Info_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_NR_PositionCalculationAssistance_r16__ext1 {
		struct LPP_NR_TRP_BeamAntennaInfo_r17	*nr_TRP_BeamAntennaInfo_r17;	/* OPTIONAL */
		struct LPP_NR_DL_PRS_ExpectedLOS_NLOS_Assistance_r17	*nr_DL_PRS_Expected_LOS_NLOS_Assistance_r17;	/* OPTIONAL */
		struct LPP_NR_DL_PRS_TRP_TEG_Info_r17	*nr_DL_PRS_TRP_TEG_Info_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_NR_PositionCalculationAssistance_r16__ext2 {
		struct LPP_NR_IntegrityServiceParameters_r18	*nr_IntegrityServiceParameters_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityServiceAlert_r18	*nr_IntegrityServiceAlert_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityRiskParameters_r18	*nr_IntegrityRiskParameters_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityParametersTRP_LocationInfo_r18	*nr_IntegrityParametersTRP_LocationInfo_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityParametersDL_PRS_BeamInfo_r18	*nr_IntegrityParametersDL_PRS_BeamInfo_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityParametersRTD_Info_r18	*nr_IntegrityParametersRTD_Info_r18;	/* OPTIONAL */
		struct LPP_NR_IntegrityParametersTRP_BeamAntennaInfo_r18	*nr_IntegrityParametersTRP_BeamAntennaInfo_r18;	/* OPTIONAL */
		struct LPP_NR_PRU_DL_Info_r18	*nr_PRU_DL_Info_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_NR_PositionCalculationAssistance_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_NR_PositionCalculationAssistance_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_NR_PositionCalculationAssistance_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_NR_PositionCalculationAssistance_r16_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_NR_PositionCalculationAssistance_r16_H_ */
#include <asn_internal.h>
