/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_A_GNSS_ProvideCapabilities_H_
#define	_LPP_A_GNSS_ProvideCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_A_GNSS_ProvideCapabilities__ext1__idleStateForMeasurements_r14 {
	LPP_A_GNSS_ProvideCapabilities__ext1__idleStateForMeasurements_r14_required	= 0
} e_LPP_A_GNSS_ProvideCapabilities__ext1__idleStateForMeasurements_r14;
typedef enum LPP_A_GNSS_ProvideCapabilities__ext2__periodicAssistanceData_r15 {
	LPP_A_GNSS_ProvideCapabilities__ext2__periodicAssistanceData_r15_solicited	= 0,
	LPP_A_GNSS_ProvideCapabilities__ext2__periodicAssistanceData_r15_unsolicited	= 1
} e_LPP_A_GNSS_ProvideCapabilities__ext2__periodicAssistanceData_r15;

/* Forward declarations */
struct LPP_GNSS_SupportList;
struct LPP_AssistanceDataSupportList;
struct LPP_LocationCoordinateTypes;
struct LPP_VelocityTypes;
struct LPP_PositioningModes;
struct LPP_ScheduledLocationTimeSupportPerMode_r17;
struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18;

/* LPP_A-GNSS-ProvideCapabilities */
typedef struct LPP_A_GNSS_ProvideCapabilities {
	struct LPP_GNSS_SupportList	*gnss_SupportList;	/* OPTIONAL */
	struct LPP_AssistanceDataSupportList	*assistanceDataSupportList;	/* OPTIONAL */
	struct LPP_LocationCoordinateTypes	*locationCoordinateTypes;	/* OPTIONAL */
	struct LPP_VelocityTypes	*velocityTypes;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_A_GNSS_ProvideCapabilities__ext1 {
		struct LPP_PositioningModes	*periodicalReportingNotSupported_r14;	/* OPTIONAL */
		long	*idleStateForMeasurements_r14;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct LPP_A_GNSS_ProvideCapabilities__ext2 {
		BIT_STRING_t	*periodicAssistanceData_r15;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct LPP_A_GNSS_ProvideCapabilities__ext3 {
		struct LPP_ScheduledLocationTimeSupportPerMode_r17	*scheduledLocationRequestSupported_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	struct LPP_A_GNSS_ProvideCapabilities__ext4 {
		struct LPP_PeriodicReportingIntervalMsSupportPerMode_r18	*periodicReportingIntervalMsSupport_r18;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_A_GNSS_ProvideCapabilities_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_idleStateForMeasurements_r14_9;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_A_GNSS_ProvideCapabilities;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_A_GNSS_ProvideCapabilities_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_A_GNSS_ProvideCapabilities_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_A_GNSS_ProvideCapabilities_H_ */
#include <asn_internal.h>
