/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_GNSS_SSR_GriddedCorrection_r16_H_
#define	_LPP_GNSS_SSR_GriddedCorrection_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LPP_GNSS-SystemTime.h"
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include "LPP_GridList-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LPP_SSR_GriddedCorrectionIntegrityParameters_r17;

/* LPP_GNSS-SSR-GriddedCorrection-r16 */
typedef struct LPP_GNSS_SSR_GriddedCorrection_r16 {
	LPP_GNSS_SystemTime_t	 epochTime_r16;
	long	 ssrUpdateInterval_r16;
	long	 iod_ssr_r16;
	BIT_STRING_t	*troposphericDelayQualityIndicator_r16;	/* OPTIONAL */
	long	 correctionPointSetID_r16;
	LPP_GridList_r16_t	 gridList_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct LPP_GNSS_SSR_GriddedCorrection_r16__ext1 {
		struct LPP_SSR_GriddedCorrectionIntegrityParameters_r17	*ssr_GriddedCorrectionIntegrityParameters_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_GNSS_SSR_GriddedCorrection_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_GNSS_SSR_GriddedCorrection_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_GNSS_SSR_GriddedCorrection_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_GNSS_SSR_GriddedCorrection_r16_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_GNSS_SSR_GriddedCorrection_r16_H_ */
#include <asn_internal.h>
