/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_LOS_NLOS_Indicator_r17_H_
#define	_LPP_LOS_NLOS_Indicator_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR {
	LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR_NOTHING,	/* No components present */
	LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR_soft_r17,
	LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR_hard_r17
} LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR;

/* LPP_LOS-NLOS-Indicator-r17 */
typedef struct LPP_LOS_NLOS_Indicator_r17 {
	struct LPP_LOS_NLOS_Indicator_r17__indicator_r17 {
		LPP_LOS_NLOS_Indicator_r17__indicator_r17_PR present;
		union LPP_LOS_NLOS_Indicator_r17__LPP_indicator_r17_u {
			long	 soft_r17;
			BOOLEAN_t	 hard_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} indicator_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_LOS_NLOS_Indicator_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LPP_LOS_NLOS_Indicator_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_LOS_NLOS_Indicator_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_LOS_NLOS_Indicator_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_LOS_NLOS_Indicator_r17_H_ */
#include <asn_internal.h>
