/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LPP-PDU-Definitions"
 * 	found in "/home/seven/kriish/3gpp_specs/37355-i70.asn"
 * 	`asn1c -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -D .`
 */

#ifndef	_LPP_HA_GNSS_Metrics_r17_H_
#define	_LPP_HA_GNSS_Metrics_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LPP_HA_GNSS_Metrics_r17__fixType_r17 {
	LPP_HA_GNSS_Metrics_r17__fixType_r17_carrier_phase_float	= 0,
	LPP_HA_GNSS_Metrics_r17__fixType_r17_carrier_phase_fix	= 1
	/*
	 * Enumeration is extensible
	 */
} e_LPP_HA_GNSS_Metrics_r17__fixType_r17;

/* LPP_HA-GNSS-Metrics-r17 */
typedef struct LPP_HA_GNSS_Metrics_r17 {
	long	 nrOfUsedSatellites_r17;
	long	*hdopi_r17;	/* OPTIONAL */
	long	*pdopi_r17;	/* OPTIONAL */
	long	*age_r17;	/* OPTIONAL */
	long	*fixType_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LPP_HA_GNSS_Metrics_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_LPP_fixType_r17_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LPP_HA_GNSS_Metrics_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_LPP_HA_GNSS_Metrics_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_LPP_HA_GNSS_Metrics_r17_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _LPP_HA_GNSS_Metrics_r17_H_ */
#include <asn_internal.h>
